### ISSUE TITLE
"Improve this doc" link broken

### ISSUE THREAD

**Issue by kjschiroo** [driftyco/ionic-site#1001]
On at least [this page of your tutorial](http://ionicframework.com/docs/v2/intro/tutorial/project-structure/)
the "Improve this doc" link in the upper right corner [404s](https://github.com/driftyco/ionic-site/edit/master/content/docs/v2/setup/tutorial/project-structure/index.md).

**Comment by perrygovier** [comment]
fixed in 854696c47e4640cf0059a785e00986e71da178fe

Thanks!
