### ISSUE TITLE
Tutorial inconsistent

### ISSUE THREAD

**Issue by kjschiroo** [driftyco/ionic-site#1002]
In the [project structure page of the tutorial](http://ionicframework.com/docs/v2/intro/tutorial/project-structure/) the file `./src/app/app.html` is shown. This does not appear to be the current version of the file generated and on [the next page](http://ionicframework.com/docs/v2/intro/tutorial/adding-pages/) the description of the same `./src/app/app.html` file that appears near the top is inconsistent with the previous page, but consistent with the actual code generated.

**Comment by MTechDE** [comment]
Can you close it @kjschiroo? I reworked the tutorial to match the current Ionic releases.
