### ISSUE TITLE
Overriding Ionic Saas Variable page broken

### ISSUE THREAD

**Issue by shawnnigel** [driftyco/ionic-site#1013]
The list on this page seems to be broken

[Overriding Ionic Saas Variables](https://ionicframework.com/docs/v2/theming/overriding-ionic-variables/)

The list is blank(with or without search term)

 [Here is the screenshot of how it looks right now](https://ibb.co/f4ANDv)

**Comment by jkeczan** [comment]
Was just logging here to mention this. Same on any browser
