### ISSUE TITLE
Products page looks wonky in chrome

### ISSUE THREAD

**Issue by wbhob** [driftyco/ionic-site#1015]
Rather than remotely try to explain what's going on, the products page (https://ionicframework.com/products/) looks like this:
<img width="1272" alt="screen shot 2017-03-12 at 12 07 17 pm" src="https://cloud.githubusercontent.com/assets/4442130/23833475/805fe66e-071c-11e7-971a-d2931d6c54e6.png">
<img width="1272" alt="screen shot 2017-03-12 at 12 07 28 pm" src="https://cloud.githubusercontent.com/assets/4442130/23833478/976b8c3c-071c-11e7-95ca-2780ad288f9d.png">

**Comment by perrygovier** [comment]
It's a cache issue with our CDN proxy. should look better now
