### ISSUE TITLE
Documentation broken for Storage

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#1016]
_From @doomtoo on March 13, 2017 23:26_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The Storage Document(https://ionicframework.com/docs/v2/storage/) is outdated and doesn't work with the current version of ionic.
The updated documentation that works is at: 
https://github.com/driftyco/ionic-storage

Mainly:
import { IonicStorageModule } from '@ionic/storage';
should be:
import { Storage } from '@ionic/storage';

and
IonicStorageModule.forRoot()
should be:
providers: [ Storage ] // Add Storage as a provider

**Expected behavior:**
It should be able to compile, but names have been changed.

**Steps to reproduce:**
Follow the official documentation: https://ionicframework.com/docs/v2/storage/ and try to compile.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
....app.module.ts(11,10): error TS2305: Module '"C:/working_dir/GroceryTrack
er/2017_02_07/grocery_tracker/node_modules/@ionic/storage/es2015/index"' has no
exported member 'IonicStorageModule'.
```

_Copied from original issue: driftyco/ionic#10762_

**Comment by mhartington** [comment]
? https://ionicframework.com/docs/v2/storage/

**Comment by mhartington** [comment]
The version of storage being used in the docs is for 2.0.0. 
Chances are the user has an older version.

**Comment by mhartington** [comment]
Closing as this is likely an outdated version.

**Comment by obermoserkitz** [comment]
Still not working, also not if following the doc.

**Comment by mhartington** [comment]
Please check your storage version in the pacakge.json and make sure it's at least 2.0.1

**Comment by michaeljcoyne** [comment]
npm install --save @ionic/storage
only updates to 1.19  I can't get this storage to work from the docs either.

**Comment by mhartington** [comment]
That sounds like an error on your end, since npm is showing 2.0.1 as what you should be getting

https://www.npmjs.com/package/@ionic/storage


But as I've already state, the docs are not wrong, just are meant for the latest storage version.

**Comment by obermoserkitz** [comment]
Oh silly me, finally **removing node_modules & npm install** fixed the Problem
Excellent work gentlemen, nice module!

**Comment by jjen009** [comment]
I am new to Ionic, and am working through the IonicAcademy 'Crash Course.'  I am using Ionic 6.16.3.  Version of @ionic/storage is 3.0.6.  When follow the course's instructions and put:

import { IonicStorageModule } from '@ionic/storage';

as the course says, VSCode says:

Module '"@ionic/storage"' has no exported member 'IonicStorageModule'.ts(2305)

I have gone on line and tried a number of things, to no avail.  Looking through the @ionic/storage module's app.module.ts I find no reference to IonicStorageModule - and nor do I find it in any of that module's files.

Do I try 'ghost's thing above - removing node_modules and npm install?  npm install *what*?

jjen009 at gmail
