### ISSUE TITLE
Deployment docs v2 android missing somethings

### ISSUE THREAD

**Issue by gatapia** [driftyco/ionic-site#1020]
I was following the instructions on [this page](http://ionicframework.com/docs/v2/intro/deploying/).

Some items missing from the Android section
- JDK is required
- `ionic platform add android` is required
- Current version of android sdk is not compatible with ionic 2, see: 
[http://stackoverflow.com/questions/42668185/could-not-find-gradle-wrapper-within-android-sdk-might-need-to-update-your-andr](http://stackoverflow.com/questions/42668185/could-not-find-gradle-wrapper-within-android-sdk-might-need-to-update-your-andr)

Other than that it installed well. Apologies for no pull request but the last item should be explored a bit by someone that knows what they are doing before being documented.

**Comment by mhartington** [comment]
We do have this page here 
http://ionicframework.com/docs/v2/resources/platform-setup/mac-setup.html

Which covers a lot more of the requirements needed.
Does this help?

**Comment by MTechDE** [comment]
Can you close it @gatapia? 
I edited the Android setup guide and added the JDK and some build/sign steps.
