### ISSUE TITLE
"Improve this doc" links in docs go to 404

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-site#1033]
The "Improve this doc" links in the currently deployed version of the v2 docs don't work:

- https://github.com/driftyco/ionic-site/edit/master/content/docs/v2/intro/installation/index.md at https://ionicframework.com/docs/v2/intro/installation/
- https://github.com/driftyco/ionic-site/edit/master/content/docs/v2/intro/tutorial/index.md at https://ionicframework.com/docs/v2/intro/tutorial/
- etc.

**Comment by mhartington** [comment]
This appears to have been fixed already.
