### ISSUE TITLE
issue: weird title for API docs

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-site#1039]
A very bizarre title for [this](http://ionicframework.com/docs/api/) page. 

> Javascript - Extend Ionic even further with the power of AngularJS - Ionic Framework

**Comment by piotrowski** [comment]
Content needs some work, too - still talks about Ionic 2 vs Ionic 2 etc.

**Comment by MTechDE** [comment]
@dylanvdmerwe can be closed I think.
