### ISSUE TITLE
docs: 404 on picker docs

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#1070]
_From @aneeskodappana on April 27, 2017 7:58_

**Type**: <span ionic-type>docs</span>
![capture](https://cloud.githubusercontent.com/assets/25400284/25473546/81865550-2b4d-11e7-8629-00b49e3834a3.PNG)

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Wrong URL reference of date picker docs</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#11396_

**Comment by mhartington** [comment]
The Picker component has been purposely ignored from the doc generation process.

**Comment by alexnu** [comment]
Hi,

Sorry if this has already been answered but I was wondering, is it in future plans to support and document the Picker element for other types besides datetime?
