### ISSUE TITLE
issue(menuController): missing API page

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-site#1080]
[This](http://ionicframework.com/docs/api/components/menu/Menu/) page says to programmatically close the menu, you should inject the `MenuController`.

However the link to `MenuController` gives a 404.
http://ionicframework.com/docs/v1/api/components/menu/MenuController

**Comment by danielsogl** [comment]
@dylanvdmerwe fixed in https://github.com/driftyco/ionic/pull/11537
