### ISSUE TITLE
"Improve this doc" link is broken

### ISSUE THREAD

**Issue by epicfaace** [driftyco/ionic-site#1088]
It links to https://github.com/driftyco/ionic-site/edit/master/_includes/fluid/component-docs/buttons.html which is broken...

**Comment by piotrowski** [comment]
Where exactly can we find this link?

**Comment by epicfaace** [comment]
Broken links are found several times on this page: https://ionicframework.com/docs/components/#buttons

**Comment by brandyscarney** [comment]
Thanks for the issue! We're taking a look. If you add `content` before `_includes` it directs properly:

https://github.com/driftyco/ionic-site/edit/master/content/_includes/fluid/component-docs/buttons.html

**Comment by mhartington** [comment]
Just pushed a fix for this, we're get these live when we redeploy the docs in a bit

**Comment by danielsogl** [comment]
@epicfaace can you close it?
