### ISSUE TITLE
Angular is running in the development mode

### ISSUE THREAD

**Issue by root-io** [driftyco/ionic-site#1093]
http://ionicframework.com/docs/components/

`Angular is running in the development mode. Call enableProdMode() to enable the production mode.`

**Comment by danielsogl** [comment]
@perrygovier that's the reason why the page loads so slow

**Comment by perrygovier** [comment]
fixed by 
https://github.com/driftyco/ionic-preview-app/commit/d233e6df51a0748704449c4257a943eedab91428
