### ISSUE TITLE
issue(docs): styling of optional tags

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic-site#1096]
_From @dylanvdmerwe on May 11, 2017 21:55_

The optional tags should really have white text inside of them.

![image](https://cloud.githubusercontent.com/assets/2852839/25973651/40f19320-36a5-11e7-8ed5-e67e0a289960.png)

_Copied from original issue: driftyco/ionic-native#1534_

**Comment by ihadeed** [comment]
@perrygovier

**Comment by brandyscarney** [comment]
This is also affecting the Framework API docs, here's the rule that is causing it:

![screen shot 2017-05-12 at 10 46 31 am](https://cloud.githubusercontent.com/assets/6577830/26003392/897fc264-3700-11e7-9595-e72ec92fa67c.png)
