### ISSUE TITLE
iOS publishing guide missing

### ISSUE THREAD

**Issue by ibes** [driftyco/ionic-site#187]
In the Guide, there are only information about Android publishing.
What about, at least, two or three sentences about iOS. Maybe it is dead simple or it is to hard to explain in the tutorial?!

The whole guide recommends to do the emulating etc. with the iOS version, because it is simpler - and in the end iOS is missing ;)

**Comment by mhartington** [comment]
Will work on something soon.

**Comment by smotru** [comment]
"soon"

**Comment by joevo2** [comment]
*soon* :frowning:

**Comment by calebhaye** [comment]
+1

**Comment by ashoksahoo** [comment]
I figured out how to eventually, but now I din have a ios dev account. Not even a Mac. Gone with the last job.

**Comment by joevo2** [comment]
I'm having a lot of difficulties now, published to play store but still having trouble with the xcode. Can't create the ipa file and tried to fix it and it says my devices provision shit thing :( so sad

**Comment by phoenix1984** [comment]
soon :frowning:

**Comment by NgYueHong** [comment]
+1
Hope for it SOON.

**Comment by FrancescoMussi** [comment]
Hello guys! 
There are some news?
I think is very important to have an official documentation about how to publish a Ionic app for Ios.
Meanwhile there are some good tutorial around?
I am searching but didn't find something really good.

**Comment by perrygovier** [comment]
Heyo, I'd like to farm this out. If someone can submit a PR, or even just provide instructions w/ pictures, it'd be a huge help. It seems like Apple changes their iTunes Connect and Xcode interface every other week.

**Comment by mhartington** [comment]
added via 19d1f27f1ee79c76fc0574a5d267ff07621ba99b
