### ISSUE TITLE
Idea : Add list of 5 top forum questions for each Javascript API in the docs

### ISSUE THREAD

**Issue by pbernasconi** [driftyco/ionic-site#218]
I think it would be very helpful to have a list of 5 - 10 questions for the Forum for each Javascript API. They would be the most popular or relevant questions, and each API (`slidebox`, `content`, `action-sheet`, etc) would have a list a the bottom of the page.

This would give a quick-link to the most relevant questions, and hopefully get people diving into the Forum a bit more, but also give solutions quickly, and maybe reduce the amount of basic forum questions which have been asked several times.

**Comment by perrygovier** [comment]
This is a good suggestion, but seeing as it hasn't been taken up or commented on in a year and a half, I'm going to close it for now.
