### ISSUE TITLE
I can't update my profile when I have edited "About me" field

### ISSUE THREAD

**Issue by sergeifedorenko** [driftyco/ionic-site#232]
Failed to load resource: the server responded with a status of 500 (Internal Server Error) http://forum.ionicframework.com/users/serg
PUT http://forum.ionicframework.com/users/serg 500 (Internal Server Error) vendor-134ec4c7a99c947213a44af37e9ce02f.js:108

Remote Address:162.159.248.203:80
Request URL:http://forum.ionicframework.com/users/serg
Request Method:PUT
Status Code:500 Internal Server Error
Request Headersview source
Accept:*/*
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8,ru;q=0.6
Connection:keep-alive
Content-Length:498
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:__cfduid=db240053070214ce62e3f4dfb039c1b8c1402905367825; _t=74339e2f5c911bb07f366f6d45153c72; _gat=1; _forum_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJWJlZjU1MjZiM2E3ZTFjYmQ5MDIzN2VlMjFiMzg1OWJjBjsAVEkiCmZsYXNoBjsAVHsHSSIMZGlzY2FyZAY7AFRbBkkiDHJlZmVyZXIGOwBUSSIMZmxhc2hlcwY7AFR7BkkiDHJlZmVyZXIGOwBUIiVodHRwOi8vZm9ydW0uaW9uaWNmcmFtZXdvcmsuY29tL0kiEF9jc3JmX3Rva2VuBjsARkkiMW0yNlZYTUxDRUFmdktsQ0lFV0tKeFVzYmdWbHpFZCtHK0NCcHNaZWZxblE9BjsARg%3D%3D--ee533a849f4aa1c6c8536b440057b9ff1e1e3cd1; _ga=GA1.2.47982121.1402993586
Host:forum.ionicframework.com
Origin:http://forum.ionicframework.com
Referer:http://forum.ionicframework.com/users/serg/preferences
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36
X-CSRF-Token:m26VXMLCEAfvKlCIEWKJxUsbgVlzEd+G+CBpsZefqnQ=
X-Requested-With:XMLHttpRequest
Form Dataview sourceview URL encoded
auto_track_topics_after_msecs:240000
bio_raw:***Loving Ionic***
website:http://this4info.com/cv/
location:Minsk
name:Sergei Fedorenko
locale:
email_digests:true
email_direct:true
email_always:false
email_private_messages:true
dynamic_favicon:false
digest_after_days:1
new_topic_duration_minutes:2880
external_links_in_new_tab:false
mailing_list_mode:false
enable_quoting:true
disable_jump_reply:false
muted_category_ids[]:-1
watched_category_ids[]:-1
tracked_category_ids[]:-1
Response Headersview source
CF-RAY:184fd11e2fed0f45-FRA
Connection:keep-alive
Content-Type:text/html; charset=utf-8
Date:Thu, 06 Nov 2014 08:10:50 GMT
Server:cloudflare-nginx
Status:500 Internal Server Error
Transfer-Encoding:chunked
X-Request-Id:1c81c8aa-421c-4127-bfaa-7dd4a652df4b
X-Runtime:0.058318

**Comment by mhartington** [comment]
fixed.
