### ISSUE TITLE
Navigation animations aren't listed in the documentation

### ISSUE THREAD

**Issue by Nesk** [driftyco/ionic-site#236]
The [ion-nav-view](http://ionicframework.com/docs/api/directive/ionNavView/) and [ion-nav-bar](http://ionicframework.com/docs/api/directive/ionNavBar/) directives mention some “animation classes” but [the provided link](http://ionicframework.com/docs/components/#animations) on those pages seems to be dead.

**Comment by mhartington** [comment]
With beta 14, these animation are no longer being used by ionic and were removed.
