### ISSUE TITLE
docs: the embedded codepen on /docs/api/directive/ionNavView/  not showing icons

### ISSUE THREAD

**Issue by micha1** [driftyco/ionic-site#248]
The problem can be fixed by changing in the codepen   :

1.  referencing  1.0.0-beta.14 instead of nightly

      changing
      //code.ionicframework.com/nightly/css/ionic.css and 
      //code.ionicframework.com/nightly/js/ionic.bundle.js  
       to 
      //code.ionicframework.com/1.0.0-beta.14/css/ionic.css  and 
      //code.ionicframework.com/1.0.0-beta.14/js/ionic.bundle.js

or 2: using the new icon names:

       ion-ios-information   instead of  ion-ios7-information 
       and ion-ios-world instead of ion-ios7-world

**Comment by mhartington** [comment]
Updated
