### ISSUE TITLE
 $ionicConfigProvider link broken on nightly tabs/ion-tabs page 

### ISSUE THREAD

**Issue by jryu01** [driftyco/ionic-site#250]
http://ionicframework.com/docs/nightly/api/directive/ionTabs/

Clicking  $ionicConfigProvider directs to following broken link:
http://ionicframework.com/docs/nightly/api/directive/ionTabs/docs/api/provider/$ionicConfigProvider/

**Comment by mhartington** [comment]
Seems to be working fine....
