### ISSUE TITLE
scroll performance on huge list

### ISSUE THREAD

**Issue by karneaud** [driftyco/ionic-site#255]
Been trying to improve the performance of using list with huge number of list items using the beta-14. 

as you can see from this demo kendallarneaud.me/mobile/android/AATT/version/0.0.2.3/ 

I've tried using my own list and infinite-scrolling implementations but on an iphone 4 running iOS 7.x. It quits the Safari browser after a certain number of times.

I'm trying to understand what the cause is but can't figure it out. hoping someone can shed some light on it as this performance issue is a huge setback for the framework

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#3486
