### ISSUE TITLE
Ion-slide-pager is still showing on the site

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-site#263]
Needs to be deleted.

https://github.com/driftyco/ionic/issues/3587

**Comment by Tzafra** [comment]
does that mean that this page (http://ionicframework.com/docs/api/directive/ionSlidePager/) should not be there, and that I should stop trying to use the ion-slide-pager?  is it no longer supported/working?

**Comment by mhartington** [comment]
Yes, ion-slide-pager is no longer in the framework and should not be used.
