### ISSUE TITLE
docs: Ionic Guide: Updating your app versionCode error

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-site#264]
_From @fe-rod on April 22, 2015 3:31_

**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In the Ionic Guide (http://ionicframework.com/docs/guide/publishing.html) there's an issue in the last step of the document (Updating your app).

It says:

"In order for the Google Play Store to accept updated APKs, you'll need to edit the platforms/android/AndroidManifest.xml file to increment the android:versionCode value"

I understand that the latest version of Cordova manages the versionCode of an app in the config.xml file. Using the current documentation is not useful as the build command regenerates the AndroidManifest.xml file every time it is executed.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3576_

**Comment by mirkonasato** [comment]
Indeed, telling users to edit the `AndroidManifest.xml` directly is not a good idea. They should only need to edit `config.xml`.

See http://forum.ionicframework.com/t/maintaining-androidmanifest-xml-in-git/26308
