### ISSUE TITLE
Ionic site scratchpad not loading. 

### ISSUE THREAD

**Issue by gortok** [driftyco/ionic-site#267]
I opened this issue [here](https://github.com/driftyco/ionic/issues/3834) and then realized it applied to this repo and not ionic.

The scratchpad located on the website at learn.ionicframework.com does not work; the console in Chrome reports 

> "Uncaught ReferenceError: IonicScratch is not defined" (line 242 of the root site document).  

Here's the relevant code:

    $.when(getTemplate('template.html'), getTemplate('style.css'),  
    getTemplate('script.js')).then(function(html, css, js) {
            var scratch = new IonicScratch({  //Uncaught ReferenceError
              el: document.getElementById('scratch'),
              width: '100%',
              height: '600px',
              html: html[0],
              css: css[0],
              js: js[0]
            });
          })

**Comment by perrygovier** [comment]
we've killed the site since its content is outdated and no longer maintained.
