### ISSUE TITLE
Remove nav-clear from the documentation

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic-site#268]
The `nav-clear` documentation is still accessible @ http://ionicframework.com/docs/api/directive/navClear/.  Since this directive was removed in [1.0.0-beta2](https://github.com/driftyco/ionic/blob/3e1ad48035f8f810ca0f466e54844a2e902217b2/CHANGELOG.md), this needs to be removed from the docs.

**Comment by marfago** [comment]
Is there any replacement for navClear directive?

**Comment by georules** [comment]
+1 I was confused why nav-clear wasn't doing anything for quite a while.
