### ISSUE TITLE
Button example in List code shows an old button style

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-site#272]
This is real obscure, but on this page, http://ionicframework.com/docs/api/directive/ionList/, the example code for swipe to show buttons has this:

<ion-option-button class="button-info"
                       ng-click="edit(item)">
      Edit
    </ion-option-button>

And is shown as red in the demo. button-info is no longer valid as a button class. It should be button-assertive.

**Comment by perrygovier** [comment]
This can be closed now
