### ISSUE TITLE
Docs for Platform Customization should mention Merges

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-site#279]
_From @cfjedimaster on September 1, 2015 14:58_

The docs here (http://ionicframework.com/docs/platform-customization/) discuss how Ionic lets you do customizations per platform. While it isn't Ionic-specific, I think it would be useful to mention the Merges feature here and link to the Cordova doc. (There isn't a great URL for that, but it can be found here: http://cordova.apache.org/docs/en/5.1.1/guide_cli_index.md.html#The%20Command-Line%20Interface)

_Copied from original issue: driftyco/ionic#4302_

**Comment by mhartington** [comment]
cc @brandyscarney

**Comment by cfjedimaster** [comment]
Doh - and I swear I looked at your repo list to find the right place. ;) Thanks!
