### ISSUE TITLE
v2 Platform docs revamp

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-site#287]

**Comment by perrygovier** [comment]
Ionic platform section's source, driftyco/ionic-native is now set up with CI and dgeni, but each plugin needs content, and possibly some UI love. 

@mhartington, please work with @tlancina to add content to these sections. 

When that's complete, lets decide if some UI/visual aid is also necessary.

**Comment by perrygovier** [comment]
Possibly demos for the sections that have browser based fallbacks.... CC @brandyscarney

**Comment by perrygovier** [comment]
this has been done
