### ISSUE TITLE
More consistent UI examples

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-site#289]
The docs for SlideBox (http://ionicframework.com/docs/api/directive/ionSlideBox/) have a great little animated gif that shows what the UI/UX is like, however this is not consistent over the rest of the docs. Pages like Modal (http://ionicframework.com/docs/api/service/$ionicModal/) do not provide any clue as to how they look. Of course, folks know what modals do, but there should still be some example as to how it will render. Popover is another example.

**Comment by perrygovier** [comment]
v2 docs have this, but I don't think we'll add this to the v1 docs

**Comment by cfjedimaster** [comment]
Fair enough. :)
