### ISSUE TITLE
apps.ionic.io app details view is not mobile-friendly

### ISSUE THREAD

**Issue by mavenius** [driftyco/ionic-site#305]
On a mobile device, when looking at an app (analytics, e.g.) the left navigation page takes up ~60% of the screen and is not hideable. When switching to landscape view, it is not possible to scroll down, and the column headings are halfway cut off on the bottom of the screen. 

I was going to fix these issue and submit a pull request, but I cannot find the repo for this subdomain; is it here somewhere that I am not seeing?

**Comment by mhartington** [comment]
These are getting a design. Closing.
