### ISSUE TITLE
"Navigating to pages" part of ionic 2 tutorial

### ISSUE THREAD

**Issue by jQrgen** [driftyco/ionic-site#308]
The tutorial doesn't explain why there is a backbutton instead of a hamburger button when you navigate to the item-details page.

https://github.com/driftyco/ionic-site/blob/master/docs/v2/getting-started/tutorial/navigation/index.md

**Comment by mhartington** [comment]
Added via https://github.com/driftyco/ionic-site/commit/7fd14984a57fe28e43d3e785560bc38aa82ecf0a
