### ISSUE TITLE
Remove concepts docs for v2

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-site#314]
This page isn't really valuable enough yet: http://ionicframework.com/docs/v2/getting-started/concepts/

 Also, concepts in the future shouldn't be restricted to npm/cli, as that's part of what made the v1 FAQ a bit harder to expand on (it was CLI FAQs only).

**Comment by drewrygh** [comment]
Updated the [concepts page](http://ionicframework.com/docs/v2/getting-started/concepts/) with a lot more content. Also, moved the random npm stuff to a [more relevant section](http://ionicframework.com/docs/v2/resources/using-npm/). 

Lmk if you think it needs more content.
