### ISSUE TITLE
ionic 2 doc, can't scroll menu with touchpad

### ISSUE THREAD

**Issue by Doehl** [driftyco/ionic-site#326]
It is not possible to scoll the menu on the ionic v2 doc site, with a laptop only using the touchpad.
There is no scroll bar, and the main page scroll bar do nothing to the menu.

It is only possible with a mouse scroll or touch screen.

**Comment by perrygovier** [comment]
I'm able to scroll when the cursor is over the menu, but this may be confusing. I'm trying to think of a way to make that more obvious or not an issue. Thoughts? CC @bensperry

**Comment by bensperry** [comment]
I'm not seeing this issue at all. I can easily scroll the whole page while my cursor is over the menu on the left.
