### ISSUE TITLE
GitHub link to Storage broken

### ISSUE THREAD

**Issue by mikewink** [driftyco/ionic-site#332]
The link to improve the Storage page is not working and results in a 404.

https://github.com/driftyco/ionic-site/edit/ionic2/docs/v2/platform/storage/index.md

**Comment by mikewink** [comment]
In general the Plattform section feels a bit strange (Jan 9th). There is only a Storage chapter and nothing else visible in the v2 docs.

**Comment by perrygovier** [comment]
Lets consolidate this under issue #287
