### ISSUE TITLE
docs: add "what's new in 2.0" 

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-site#338]
_From @brandyscarney on October 20, 2015 14:36_

It would be good to have a section in the docs that explains what we've changed/added in 2.0 that differs from 1.0. Maybe this could go in the migration section? 

_Copied from original issue: driftyco/ionic2#320_

**Comment by mhartington** [comment]
_From @adamdbradley on October 26, 2015 15:19_

Good idea. I think the migration section would be a good location for this. cc/ @mhartington

**Comment by mhartington** [comment]
_From @brandyscarney on November 6, 2015 17:16_

We should list the components that are new, and what has been changed or added to existing components.

For example:

New: segment, searchbar
Changed: menu can now be reveal, overlay, etc.

**Comment by perrygovier** [comment]
I believe the Migration and Concepts sections sufficiently cover this
