### ISSUE TITLE
Add docs for npm, modules, bundling, es6 imports in Resources

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-site#339]
_From @tlancina on November 16, 2015 16:18_

Explain npm, modules, bundling, es6 imports in Resources, link to them in tutorial, getting started, etc.

_Copied from original issue: driftyco/ionic2#538_

**Comment by mhartington** [comment]
This should be in the glossary already.

**Comment by perrygovier** [comment]
We could add modules, and link to them from the tutorial/getting started when they're mentioned.
