### ISSUE TITLE
Getting started tutorials discuss js but display ts

### ISSUE THREAD

**Issue by rtpHarry** [driftyco/ionic-site#347]
The first page in the series just mentions that `--ts` is an option, it doesn't instruct the reader to use it:

http://ionicframework.com/docs/v2/getting-started/tutorial/

Then further along the rest of the code samples refer to them like "if we look in `app.js`" but the code sample has TypeScript code in it:

http://ionicframework.com/docs/v2/getting-started/tutorial/adding-pages/

**Comment by perrygovier** [comment]
@mhartington, it's my understanding that we're going all in on TS. Check with @adamdbradley to make sure that's the case, and if so, lets update the docs to say TS across the board.

**Comment by mhartington** [comment]
Will note that that even if dev's choose to use JS instead TS, the code would stay mostly the same. Since all valid Javascript is valid typescript, this is all good.

**Comment by perrygovier** [comment]
I think this can be closed then.
