### ISSUE TITLE
docs/guide/publishing.md points to old config.xml file documentation

### ISSUE THREAD

**Issue by stianlagstad** [driftyco/ionic-site#356]
Change http://cordova.apache.org/docs/en/4.0.0/guide_platforms_android_config.md.html#Android%20Configuration -> http://cordova.apache.org/docs/en/latest/guide/platforms/android/config.html ?

**Comment by perrygovier** [comment]
done in 3d273fe391d45b3e1854d9140379fd49e04a81fb
Thanks!
