### ISSUE TITLE
Add page by page navigation footer

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#370]
Per slack chat w/ Ben

**Comment by perrygovier** [comment]
![](https://files.slack.com/files-pri/T024WJZKU-F0L3XTJ0Z/pasted_image_at_2016_02_02_01_33_pm.png)

**Comment by perrygovier** [comment]
![pasted_image_at_2016_02_02_01_33_pm_1024](https://cloud.githubusercontent.com/assets/571056/12761694/9c599472-c9b1-11e5-9cca-158aac8a6f29.png)

**Comment by mhartington** [comment]
It is done
