### ISSUE TITLE
remove Tutorial templates button

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#378]
Find a better way to communicate the templates than the accordion button.

**Comment by perrygovier** [comment]
<img width="586" alt="screen shot 2016-02-02 at 1 50 21 pm" src="https://cloud.githubusercontent.com/assets/571056/12762233/ebcbd6bc-c9b3-11e5-8c7e-72bb604e354c.png">

**Comment by perrygovier** [comment]
^that

**Comment by mhartington** [comment]
We can probably just remove the according and add it as a note.

<img width="712" alt="screen shot 2016-02-05 at 3 15 41 pm" src="https://cloud.githubusercontent.com/assets/2835826/12857995/5bb0a85e-cc1b-11e5-869b-48622f97843f.png">

**Comment by perrygovier** [comment]
make it so

**Comment by mhartington** [comment]
done
