### ISSUE TITLE
Find new design for folder structure graphics

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#380]

**Comment by perrygovier** [comment]
For example http://ionicframework.com/docs/v2/getting-started/migration/

**Comment by perrygovier** [comment]
Lets stick w/ markdown but lets use the `tree` command to generate something more consistent
http://linux.die.net/man/1/tree

@mhartington can you replace the folder demos w/ have w/ ones generated by the `tree` command?

**Comment by mhartington** [comment]
Oddly enough, those were generated with the tree command
