### ISSUE TITLE
Spice up main API page

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#389]
@mhartington, can you think of any content we can add to this page.

@bensperry, are there any graphics we can add that you help this page be more interesting?

**Comment by mhartington** [comment]
I can think of some stuff, I can push it tomorrow

**Comment by mhartington** [comment]
I pushed some changes a bit ago. We can tweek it a bit more if needed

**Comment by bensperry** [comment]
Let's also remove the "AngularJS Extensions" heading and use something more appropriate for the landing page of our API section. Maybe something as simple as "Ionic API" ?

**Comment by perrygovier** [comment]
![api-graphic](https://cloud.githubusercontent.com/assets/571056/12822693/d8cec782-cb2e-11e5-9785-6358202ff010.png)

**Comment by perrygovier** [comment]
^graphic to be used
