### ISSUE TITLE
Rename Ionic Platform (the cordova plugins) to Ionic Native, Plugins, something...

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#392]
With Ionic Platform being used for backend services. Should we call the integrated plugins something else?

**Comment by mlynch** [comment]
I'm fine with Native for now.

**Comment by perrygovier** [comment]
So it written. Ok, time to update the docs so that "Ionic Platform" in reference to Cordova plugins and their TS wrappers are "Ionic Native"

**Comment by mhartington** [comment]
Closing for now. Docs now reference Ionic Native. In progress, adding docs
