### ISSUE TITLE
docs: combine menuToggle, menuClose into menu

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#393]
It has been decided:

https://github.com/driftyco/ionic/issues/5307#issuecomment-179498103

**Comment by perrygovier** [comment]
Make MenuToggle and menuClose private, and port all their content and docs over to menu

**Comment by perrygovier** [comment]
I disagree w/ this. in components they should be all in one section, but i API, they should be separate.

**Comment by perrygovier** [comment]
@brandyscarney, can you interlink these more rather than combine them?

**Comment by brandyscarney** [comment]
@perrygovier 👍

**Comment by brandyscarney** [comment]
I split Menu and MenuController into separate docs and added more explanation to the Menu docs on MenuToggle and MenuClose: http://ionic-site-staging.herokuapp.com/docs/v2/api/components/menu/Menu/

Should be good to go!
