### ISSUE TITLE
Platform menu hyperlinks are invalid

### ISSUE THREAD

**Issue by toepoke** [driftyco/ionic-site#396]
Hi,

On this page:
http://ionicframework.com/docs/v2/platform/

The links in the left hand side menu are incorrect (barcode, battery, etc).  Tried making an educated guess but couldn't work out what they should be.

Only tried using the "Improve this doc" link, but that gave a 404 too :-)

Hope this helps.

Kind regards,
Franz.

**Comment by mhartington** [comment]
These are being worked on.

**Comment by perrygovier** [comment]
I'm going to close this. Platform is being renamed to native, and will be released soon.
