### ISSUE TITLE
Update demos

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#397]
API Demos:

Events:
- [x] Make a login page that hides menu items

Id:
- [x] Show multiple menus diff IDs

Input:
- [x] Show different kinds of inputs

Items:
- [x] Show different kinds of items

ItemSliding:
- [x] Show different kinds of sliding items
- [x] Add to Option as well

LocalStorage:
- [x] Button block messes up icons
- [x] Select boxes

Menu:
- [x] Multiple Menus

Navbar:
- [x] Show some navbars

RadioButton/RadioGroup:
- [x] Make multiple radio lists

Searchbar:
- [x] Show different kinds of Searchbars

Segment:
- [x] Show different kinds of segments

Select:
- [x] Random selects

SQLStorage:
- [ ] Look into this

Tab/Tabs:
- [x] Show different tab scenarios

Textarea:
- [x] Different textareas

Title:
- [x] Update toolbar scenarios to look better

Random:
- [x] Right now the demos that pass parameters actually are only passing one parameter. We should use a list with selects so they can pass multiple parameters and then show the code on the next page.

Examples:
Modals
Nav Params

Moved some to these issues: 

https://github.com/driftyco/ionic-site/issues/395 
https://github.com/driftyco/ionic-site/issues/394

**Comment by brandyscarney** [comment]
@drewrygh I'm currently working on searchbar/segment but if you want to tackle any others on this list just coordinate with me. :smile:

**Comment by perrygovier** [comment]
The only remaining task here should be part of the ionic-native tasks
