### ISSUE TITLE
docs: add utility section for text transformation and padding attributes

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#398]
We should have a util section that includes the different attributes you can use:

https://github.com/driftyco/ionic/blob/2.0/ionic/components/app/typography.scss#L101-L137
https://github.com/driftyco/ionic/blob/2.0/ionic/util/util.scss#L15-L95

padding attributes are in each individual mode content:
https://github.com/driftyco/ionic/blob/2.0/ionic/components/content/content.ios.scss#L29-L62

also will be adding some other attributes in this issue: https://github.com/driftyco/ionic/issues/5283

**Comment by perrygovier** [comment]
This should be a "CSS utilities" section in the theming section
