### ISSUE TITLE
Alert Docs: Create table for all option properties

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#405]
Create a table on the alert docs for all the properties, descriptions and defaults, that can be added to the alert options.

Options:
    title?: string,
    subTitle?: string,
    message?: string,
    cssClass?: string,
    enableBackdropDismiss?: boolean,
    inputs?: Array<any>,
    buttons?: Array<any>

Input Options:
      type?: string,
      name?: string,
      placeholder?: string,
      value?: string,
      label?: string,
      checked?: boolean,

Button Options:
    text
    handler
    cssClass
    role

**Comment by mhartington** [comment]
And it is done! 

<img width="1463" alt="screen shot 2016-03-07 at 12 42 28 pm" src="https://cloud.githubusercontent.com/assets/2835826/13577830/8a579578-e462-11e5-925c-830c8ebb575c.png">
