### ISSUE TITLE
Modals example is missing Page import

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic-site#411]
1) The [Modals](http://ionicframework.com/docs/v2/components/#modals) has this part:
```
import {Modal, NavController} from 'ionic/ionic';

@Page({
  template: `
  <ion-content padding>
    <h2>I'm a modal!</h2>
    <button (click)="close()">Close</button>
  </ion-content>`
})
class MyModal {
  constructor() {
  }
}
```

For upper part to work, the `Page` needs to also be imported from `ionic/ionic`. 

2) [Modal component docs](http://ionicframework.com/docs/v2/api/components/modal/Modal/) has also false syntaxing with markdown. 

3) There's also no info on how to retrieve parameters in modal after we send them to modal using `let modal = Modal.create(ModalFilter, {data: 'param'});`
:+1:

**Comment by mhartington** [comment]
fixed via https://github.com/driftyco/ionic/commit/2621a87f5cecb125014a1ce18671afed8e36f913
