### ISSUE TITLE
Translate - Improve doc

### ISSUE THREAD

**Issue by Enzo-bianchi** [driftyco/ionic-site#412]
Hi, I want improve the docs from here  http://ionicframework.com/docs/v2/utils/translation/ 
but 404 :/.
So,
For the translation you have to add also :

`import {Translate,TranslatePipe}`
and
`@
Page({
    templateUrl: 'build/pages/abc/abc.html',
    pipes: [TranslatePipe]
})`

**Comment by mhartington** [comment]
The link is to a rather old and early stage of ionic 2. The translation code has been removed from ionic as it's more fitting for this to come from either angular directly or another library, such as [ng2-traslate](https://github.com/ocombe/ng2-translate)
