### ISSUE TITLE
bug: Folder structure issue

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#417]
_From @RIanDeLaCruz on February 11, 2016 13:42_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Based on the documentation, the app folder should be inside the www folder. Instead, when I create a project, the app and www folders are siblings in the root folder.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5412_

**Comment by brandyscarney** [comment]
_From @adamdbradley on February 11, 2016 14:47_

Sorry, we must have our docs outdated. Which page are you seeing that on? cc @mhartington

**Comment by RIanDeLaCruz** [comment]
I am seeing it here: http://ionicframework.com/docs/v2/theming/theming-your-app/
and here: http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/

**Comment by mhartington** [comment]
Updated via https://github.com/driftyco/ionic-site/commit/b5492af9715baf1a68f8c8f646f0575ec5879ebf
