### ISSUE TITLE
docs: Various issues related to V2 docs

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#418]
_From @cfjedimaster on February 10, 2016 20:33_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I created a Gist of my issues:

https://gist.github.com/cfjedimaster/ab78eb3e0adbef982098</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5398_

**Comment by mhartington** [comment]
done
