### ISSUE TITLE
docs: Ionic v2 docs for plugins are unavailable

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#419]
_From @matheuscas on February 10, 2016 20:20_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I make a search for "Ionic Native" and click on it, I receive this:
Cannot GET /docs/v2/platform/applinks/

It seems to be like this in all links about Ionic Native.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5395_

**Comment by brandyscarney** [comment]
_From @tlancina on February 10, 2016 20:24_

Thanks for the issue, Ionic Native is still under development and the docs will go live soon :)

**Comment by brandyscarney** [comment]
_From @matheuscas on February 10, 2016 20:28_

Oh, sorry about that. I thought it would have some docs for the announcement for the new beta.

**Comment by tlancina** [comment]
Docs are up!
