### ISSUE TITLE
V2 - Docs on changing header colors, etc

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-site#423]
Unless I am missing it, the current docs are don't explain how to change the color of nav headers, etc.  Would like to see some documentation around this.  The theming docs suggest changing the primary variable, but that does not do it.

**Comment by jgw96** [comment]
@danbucholtz You can currently configure the color of toolbars, tabs, etc. This was broken in a past issue (couldnt change the color of the tabs on android) but now its fixed and simply just works <ion-tabs primary>. Is there a specific element you were wanting to style but were having issues with?
