### ISSUE TITLE
ion-item-sliding demo in components, show how to close

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-site#424]
ion-item-sliding only has a demo in the API section versus the components section.  It makes sense to show the demo within the list components.

It would be nice to have a demo showing how to close it as well.

**Comment by perrygovier** [comment]
The demo has been added to components
http://ionicframework.com/docs/v2/components/#sliding-list

And the API docs mention how to programmatically close them now
http://ionicframework.com/docs/v2/api/components/list/List/
