### ISSUE TITLE
Markdown links not working in return value descriptions

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-site#435]
![image](https://cloud.githubusercontent.com/assets/804331/13091945/14d95fc4-d4c3-11e5-8bc3-02f1621c6800.png)

**Comment by perrygovier** [comment]
On it, are you on a branch? Can you commit this to the branch so I can test against it?

**Comment by tlancina** [comment]
Thanks, just pushed to master since Native isn't in the menu yet: https://github.com/driftyco/ionic-site/commit/bd5389788e02f2d5fce967a8642516848ed6de39

**Comment by perrygovier** [comment]
woop tagged that commit wrong. all the same, fixed
