### ISSUE TITLE
V2 - Custom Back button text

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-site#436]
I am not seeing any documentation on how to change the back button text.  It's always just "Back" by default for me.

**Comment by mhartington** [comment]
Do the config docs help you at all? 

http://ionicframework.com/docs/v2/api/config/Config/

**Comment by danbucholtz** [comment]
Ahh, yeah we could definitely use that, or use the navController and set the back button text that way.  I wonder if there is a way to get that automatically and have it work like V1 where it inherits the title/label from the navbar and automatically applies it to the back button.

Thanks for the input.  Go ahead and close if you'd like.

**Comment by danbucholtz** [comment]
@mhartington, I am thinking we should re-open this.

Looking at iOS, every time I push a new page onto the UINavigationController stack, it uses the previous' pages title as the back button title.  I am looking at the docs and nothing explains how to accomplish this use case easily.

This is also a different behavior from V1.  I suspect many users migrating to V2 will want documentation on how to accomplish this behavior easily.

Appreciate it.

Thanks,
Dan
