### ISSUE TITLE
V2 - Documentation on events

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-site#438]
I am looking for some documentation on events like on-hold, on-drag, etc.  I don't see any of it on the V2 site.

http://ionicframework.com/docs/api/directive/onHold/ equivalent in V2.

**Comment by danbucholtz** [comment]
@perrygovier, does Sprint 2/26 mean it starts 2/26, or ends 2/26?

**Comment by perrygovier** [comment]
Ends on 2/26. It's a rough goal, no promises.

**Comment by danbucholtz** [comment]
I understand - just trying to ballpark.  Cool man, appreciate the openness.

**Comment by danbucholtz** [comment]
Hey team - any update on this?

**Comment by perrygovier** [comment]
Hey Dan, that'll teach me to add dates to a sprint. Another project has gotten bumped up priority. This is high on the list for ionic-site but it might be a week before we can get to it.

**Comment by danbucholtz** [comment]
Hey no worries - I just want to make sure the team is aware that this is a pretty major issue for app developers.  Maybe you guys could add a quick example to the conference app and worry about documenting it later?  Or just show in code how they're accessed?  I cannot find anything in my repository searching.

**Comment by perrygovier** [comment]
No worries. v2 wraps hammer.js. Here's an example of that wrapper, gesture,  being used internally:
https://github.com/driftyco/ionic/blob/2.0/ionic/gestures/drag-gesture.ts

**Comment by perrygovier** [comment]
driftyco/ionic#5663 Needs to be resolved first.

**Comment by perrygovier** [comment]
@mhartington with beta 4 out, this should be ready to be added

**Comment by rubimazaki** [comment]
And still... no docs about gestures

**Comment by danbucholtz** [comment]
@rubimazaki,

There are docs right here.
http://ionicframework.com/docs/v2/components/#gestures

Thanks,
Dan

**Comment by rubimazaki** [comment]
Kind of disgraceful conduct you have...

You call that docs? This is more like a joke.

**Comment by danbucholtz** [comment]
Hi @rubimazaki,
[
Hammer.js](http://hammerjs.github.io/) is built-in to Angular 2 as a first class citizen.

Developers use the standard event template syntax to listen for gestures.  For example,

```
<div (swipe)="mySwipeHandler($event)"></div>
<div (tap)="myTapHandler($event)"></div>
<div (pan)="myPanHandler($event)"></div>
```

This is how gestures work in Ionic 2 and Angular 2. Is there something else that you had in mind for the docs? We're always open to suggestion, and there is always the option of you submitting a PR with the changes you'd like to see as well.

Thanks,
Dan

**Comment by rubimazaki** [comment]
That does look much better than the docs :)

But that won't help anybody who tries to do something more complicated. And I did try the (pan) for example, which didn't fit for my purpose. What did the trick finally was the (private?) class UIEventHandler that the range component uses. I guess that what I thought would help me was the Gesture class, but there are no (real) docs on how to use/extend it nor UIEventHandler.

What I am saying? REOPEN this issue. It is really not resolved at all.

**Comment by danbucholtz** [comment]
Hi @rubimazaki,

Just like in iOS's Cocoa Touch framework, Ionic has some internal utilities and methods that are not documented and not meant to be used by the public. UIEventHandler falls into that bucket at the current time.

In a future release/iteration we may have additional support for gestures, but right now the recommended approach is to use Hammer using the event binding syntax.

Thanks,
Dan

**Comment by rubimazaki** [comment]
Yupp. But even using the basic gesture binding is not very straight forward without a basic reference.

**Comment by manucorporat** [comment]
@rubimazaki we might release some public API for UIEventManager or GestureController used internally, but not yet. It is a powerful API but too low level to be used correctly in most of the cases.

A lot of design is needed to release that as a public API, definitely it is something we have talked about.

**Comment by rubimazaki** [comment]
What I am saying - Gesture class, even if not exposed itself (it is public) should have some documentation. For example: which events are supported (tap, swipe, pan...) and how to use them. Current situation is that there is one (kind of lonely...) paragraph with broken link to demo. This needs fixing...

**Comment by mhartington** [comment]
Yes, it should have documentation, when it is usable and consumable for outside devs. Until, it's not meant for public usage.

As for the demo links, look again. They have been fixed and pushed.

**Comment by rubimazaki** [comment]
Great you fixed the link.

BTW - You are all doing a holy work with Ionic2 :)
Don't think that I don't appreciate. Just the docs in the Beta (I mean RC :)) are somewhat on the edge.

Thanks!

**Comment by ehorodyski** [comment]
There is still not good documentation on Ionic gestures...
