### ISSUE TITLE
docs: $ionicViewSwitcher public API docs is missing

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#440]
_From @epaezrubio on February 2, 2016 10:20_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Documentation for this service is missing https://github.com/driftyco/ionic/blob/master/js/angular/service/viewSwitcher.js

I will submit a PR soon</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5291_

**Comment by adamdbradley** [comment]
_From @jrencz on February 5, 2016 19:41_

@epaezrubio this service is marked as private - this means it does not need its public api to be documented.

Angular does not provide DI scoping so everything that is exposed to DI is public in fact. The only way to express that some parts of Ionic are not meant for developers to make their own code depandant on is to mark those services as `@private` and NOT provide publicly available documentation. This leaves ionic developers certain amount of freedom in implementing features.

**Comment by perrygovier** [comment]
Closing since this intended to be private

**Comment by Arxi** [comment]
If I understand it correctly, using `$ionicViewSwitcher` is the only way to set the next navigation direction and transition when changing states programatically via `$state.go`, e.g.:

```
$ionicViewSwitcher.nextDirection("back");
$state.go("dashboard")
```

If this service is considered private, is there any public alternative? I know about nav-direction and nav-transition directives but those can't be used in this dynamic example.
