### ISSUE TITLE
Input Properties

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#445]
Create an input properties page on learnangular2.com, then have a link to it on every input properties header:
![image](https://cloud.githubusercontent.com/assets/452425/13155947/ce90c8ac-d645-11e5-81f3-8a3afdb77888.png)

Simple explanation what they are, and how to use them, and then a link to angular's full docs.

**Comment by mhartington** [comment]
http://learnangular2.com/inputs/

Added
