### ISSUE TITLE
docs: Improve v2 migration docs

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#449]
_From @ricsmania on February 19, 2016 12:39_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The migration docs (http://ionicframework.com/docs/v2/getting-started/migration/) do a good job explaning how to project should be structured the make the migration easier. But they don't provide actual steps to migrate the app. More specifically, there is nothing about how to bootstrap using the UpgradeAdapter.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5528_

**Comment by mhartington** [comment]
Theres no 'one way' to upgrade an app. Everyones miles will vary.

**Comment by ricsmania** [comment]
@mhartington I think I wasn't very clear. It's not about upgrading an entire application to v2, actually my question is how to use Angular's UpgradeAdapter to be able to use components both from Angular 1 and Angular 2.

Just to be clear, what I am asking for is a documentation such as this but for Ionic: https://angular.io/docs/ts/latest/guide/upgrade.html#!#bootstrapping-hybrid-angular-1-2-applications

Will Ionic provide its own UpgradeAdapter?

The documentation only provides steps to prepare an application for the upgrade, but doesn't conclude with the steps on how to actually migrate a v1 application to a hybrid v1+v2 application.

**Comment by mhartington** [comment]
Ionic is not providing it's own UpgradeAdapter. 
Looking over UpgradeAdapter, it just doesn't seem like a process that will work well for v1 and v2 ionic apps. 

The recent upgrade to ng1.5x though will provide a better upgrade experience IMO and when we release the next version of V1, I'll add a note about that in the migration docs.
