### ISSUE TITLE
Concerning the docs in the website

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#450]
_From @Bandito11 on February 19, 2016 1:33_

This is more of a suggestion. I was recommending my friend (he's a noob) to try ionic2 in order to play with it, but he told me he did everything in the steps and no luck. The problem was he didn't know he had to install node.js on his computer. 

My recommendation would be to make complete instruction for noobies that are just starting to use the ionic CLI. Or at least tell them to install nodejs and 'npm install cordova' and whatever else is needed!

_Copied from original issue: driftyco/ionic#5520_

**Comment by mhartington** [comment]
Added note about installing node 
https://github.com/driftyco/ionic-site/commit/be5854a421d6fed396c58adccb9417b4960dcc68
