### ISSUE TITLE
API demos

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#453]
- ActionSheet
 - [x] Add padding to Action Sheet content (my bad I removed this) 
 - [x] Remove custom animation button or add a custom animation demo

- Alert
 - [x] Add padding to Alert content (my bad I removed this) 
 - [x] Remove custom animation button or add a custom animation demo

- Icon
 - [x] Maybe toss some more random colors into the demo

- Item
 - [x] Look into why the radio buttons are checking both (under Silence header) - created new issue https://github.com/driftyco/ionic/issues/5659

- Local Storage
 - [x] Why is the demo adding random chartbeat keys
![screen shot 2016-02-19 at 11 07 39 am](https://cloud.githubusercontent.com/assets/6577830/13181034/106ed954-d6f9-11e5-933b-851d4a8434fa.png)

- Modal
 - [x] Clean up the code block on modal so it isn't indented
![screen shot 2016-02-19 at 11 10 07 am](https://cloud.githubusercontent.com/assets/6577830/13181100/5d0f62d8-d6f9-11e5-81dd-f53a423ee2c3.png)

- NavParams
 - [x] Same as Modal - clean up code block

- RadioButton/RadioGroup
 - [x] Shouldn't be able to select multiple values here - created new issue https://github.com/driftyco/ionic/issues/5659

- Refresher
 - [x] Refresher doesn't work at all on desktop, we need to figure out a way to present this in the demo

- Segment
 - [x] See if you can remove the inline styling I added since I added this to the framework & it is now breaking Android :wink: 

- Tab/Tabs
 - [x] Maybe add some badges to the tabs higher up and add colors to the existing toolbars (similar to how we do button colors)

- Infinite Scroll
  - [x] Add Infinite Scroll demo

- All
  - [ ] Fix the Sass files

See me for any questions. :smile:

**Comment by jgw96** [comment]
I would like to take some of these if there not already taken?

**Comment by jgw96** [comment]
@brandyscarney @drewrygh looks like some of these tasks may already be done?

**Comment by brandyscarney** [comment]
@jgw96 I'm not sure, all of the API demos are here: https://github.com/driftyco/ionic/tree/2.0/demos

It doesn't look like any of these have been done.

**Comment by jgw96** [comment]
@brandyscarney Youre correct, wasnt looking in the right place, my bad

**Comment by brandyscarney** [comment]
I completed some more of these tasks. @drewrygh can you clean up the Sass to be more like the conference app? I want to be able to define the colors similar to the conference app, and we may want to add Sass files for individual demos.

**Comment by perrygovier** [comment]
Does the chart beat cause a problem? We use it for analytics. Odd that it's injecting itself in to iframes, but it shouldn't be a concern would it?

**Comment by brandyscarney** [comment]
It doesn't cause a problem it's just confusing to the user when we are showing them what gets added to local storage and it is adding displaying keys they didn't add. We just need to only display keys that are in the options to add: http://ionicframework.com/docs/v2/api/platform/storage/LocalStorage/

**Comment by perrygovier** [comment]
I'm not sure which even chart beat adds itself to the iframe, probably DOMReady. If we add a little JS to wipe out chart beat after that event, we should be fine. No reason to have it there anyways.

**Comment by brandyscarney** [comment]
I think it might be better to only display the keys that are available to add in the select dropdown. Since we don't know what other keys might be added in their local storage. Let me know if you disagree!
