### ISSUE TITLE
Set anchors on all headers and method names

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#455]
I'd like to be able to link to specific section in the docs, or a specific method. For example, I'd like to link to the Usage section on the alert path with: `http://ionicframework.com/docs/v2/api/components/alert/Alert/#Usage` and the link would jump the user directly to Usage section.

Same for methods. I'd like to be able to link to the `setTitle` method with: `http://ionicframework.com/docs/v2/api/components/alert/Alert/#setTitle`

**Comment by adamdbradley** [comment]
Additionally, like github markdown files that automatically create an anchor for each header, the header should have a link icon next to it when the user hovers:
![image](https://cloud.githubusercontent.com/assets/452425/13200548/b2922cee-d812-11e5-843d-9b1f3520ee49.png)

**Comment by perrygovier** [comment]
Done!
