### ISSUE TITLE
docs: Reference of the slide component needs to be more detailed 

### ISSUE THREAD

**Issue by pjc0247** [driftyco/ionic-site#458]
Recently, I had a few problems with your slide components.
I think there are some improvement points in the API Reference & Demo usages.

* How to specify the raw option values. (I know that there is an `option` property to specify the raw options. but it would be great to make some demo usages for beginners like me.)
* How to change index at runtime. (In Swiper.js, they already have an API to swipe manually by the script not an user's input. Is there any wrapping methods in ionic2? I coudn't find anything in your docs.)

Thanks.

**Comment by mhartington** [comment]
So we currently need to hold off until this is finished

https://github.com/driftyco/ionic/issues/5508

Based on the ideas from 
https://github.com/driftyco/ionic/issues/5189#issuecomment-178133607

**Comment by brandyscarney** [comment]
Thanks for the issue @pjc0247! I've updated the Slides docs with more explanation, usage and documentation behind the methods exposed. Please let me know if you have any feedback! The docs can be seen on our staging site until we publish them live: http://ionic-site-staging.herokuapp.com/docs/v2/api/components/slides/Slides
