### ISSUE TITLE
Buttons in toolbar

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#461]
In the button component docs we show how <ion-buttons> work in the toolbar, but to me its a little confusing for that to be in the button component docs and not the toolbar docs too.

**Comment by jgw96** [comment]
@brandyscarney Id love to hear your thoughts on this, would this be crowding up the toolbar docs too much?

**Comment by brandyscarney** [comment]
@jgw96 Yes, I agree. I was confused the first time I saw the "Buttons in Components" docs. I think the toolbar docs should be split into sections highlighting the different components you can place in a toolbar.

- Buttons in a toolbar are styled clear by default
- Show how to style buttons solid, outline, etc.
- Segment in a toolbar
- Searchbar in a toolbar

Similar to the API demo but broken into sections: http://ionicframework.com/docs/v2/api/components/toolbar/Toolbar/

I think we really need to get across the first point, as it is probably going to cause some confusion. Adding @bensperry for opinion.

Also, this issue has a task for cleaning up the toolbar demo: https://github.com/driftyco/ionic-site/issues/451 maybe this could be done as part of that.

**Comment by jgw96** [comment]
Totally agree. It makes sense to combine prettying up the toolbar demo as part of this issue. The toolbar docs is pretty lacking at this point, so any change we make is going to be an improvement (:

**Comment by drewrygh** [comment]
Thanks @jgw96 - closing this since I added it as a subtask of #451
