### ISSUE TITLE
Alert: message should be body

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#469]
Alert docs: body should be message. body is not an accepted property of Alert.

<img width="622" alt="screen shot 2016-02-27 at 4 53 21 pm" src="https://cloud.githubusercontent.com/assets/8823093/13375922/af1c9954-dd72-11e5-821b-fc98a288e6b8.png">

**Comment by jgw96** [comment]
@brandyscarney can you confirm me on this? If so ill fix it

**Comment by brandyscarney** [comment]
@jgw96 Yes, `body` was renamed to `message`. It will still work with `body` but I believe a deprecation message will appear.

**Comment by jgw96** [comment]
Yeah, in vs-code you get a message from intellisense about it. Was just
wondering if we should adjust the docs to show this?

> On Mar 1 2016, at 5:11 pm, Brandy Carney &lt;notifications@github.com&gt;
wrote:  

>

> [@jgw96](https://github.com/jgw96) Yes, body was renamed to message. It will
still work with body but I believe a deprecation message will appear.

>

> —  
Reply to this email directly or [view it on
GitHub](https://github.com/driftyco/ionic-site/issues/469#issuecomment-1909555
05).![](https://github.com/notifications/beacon/AIahNeKy0X__YT9_vjqAnVKsKvucaZ
ysks5ppMeLgaJpZM4Hkouy.gif)

**Comment by brandyscarney** [comment]
@jgw96 Yes. Docs should use message. :smile:
