### ISSUE TITLE
docs: Ionic V2 Example error

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#470]
_From @kuntal-b on February 27, 2016 6:15_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I am using FF 43.0.1 some example like 
http://ionicframework.com/docs/v2/components/#alert
http://ionicframework.com/docs/v2/components/#select
not working .I found bellow java script error in Firebug console

TypeError: self.ele.animate is not a function.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5630_

**Comment by brandyscarney** [comment]
_From @jgw96 on February 27, 2016 19:21_

I can also confirm this error in Firefox 44. Im thinking maybe its related to the web animation api support in firefox.

**Comment by perrygovier** [comment]
This is fixed in the latest version
