### ISSUE TITLE
How setting up and organizing ionic with require.js 

### ISSUE THREAD

**Issue by PterPmnta** [driftyco/ionic-site#476]
I would like to know how to configure the dependencies placed in the default header to download using ionic npm , that order should wear and how to organize the new files to be added

structur folder

```
  <!-- ionic/angularjs js -->
    
    <script src="lib/ionic/js/ionic.bundle.min.js"></script>
    
    <script src="lib/ngCordova/dist/ng-Cordova.js"></script>
    
    <script src="cordova.js"></script>
    
    <script src="js/app.js"></script>
```

[https://cdn.discourse.org/ionicframework/uploads/default/original/3X/5/4/543ab2dff1e4520cc08d19648b403e42607c2f24.jpg](url)

Was set up but fails to organize the shim

```
require.config({
    
    baseUrl: 'www',
    
    paths : {
        
        ionic: 'lib/ionic/js/ionic.bundle',
        ngCordova: 'lib/ngCordova/dist/ng-cordova',
        cordova: 'cordova',
        angular: 'lib/angular/angular',
        app: 'js/app'
        
    },
    
    shim:{
        
        ionic: {exports: 'angular'},
        ngCordova: {exports: 'ngCordova'},
        cordova: {exports: 'cordova'},
        angular: {exports: 'angular'}
        
    }
  
});
```

[https://cdn.discourse.org/ionicframework/uploads/default/optimized/3X/c/0/c0f2ab8689cce401c4f3360abe626b4e40ad41a9_1_690x368.jpg](url)

is not whether routes are the folders that are wrong , but I think it's wrong settings of the shim

`<script src="lib/require/require.js" data-main="lib/main">`

**Comment by mhartington** [comment]
Hi there. It seems you opened a framework related question on the ionic-site repo. Sadly not the correct place, so I'm afraid Im going to have to close this. :disappointed: 

But the issue you've brought up has been addressed before.

https://github.com/driftyco/ionic/issues/1448
