### ISSUE TITLE
docs(demos): update Action sheet demos for both component & API 

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#478]
Destructive button should be on the top

**Comment by jgw96** [comment]
@brandyscarney @drewrygh i can knock this out real quick?

**Comment by brandyscarney** [comment]
@jgw96 if you want to just tag me in it so I can merge it tomorrow. :smile:

**Comment by jgw96** [comment]
@brandyscarney sounds like a plan haha (:
