### ISSUE TITLE
docs: TS all the things!

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-site#479]
Update the tutorial to remove constructor types and add 
```
static get parameters(){ 
  return [[NavController], [NavParams]]
}
```

**Comment by perrygovier** [comment]
For now we're going all in on TS. We should reconsider this when/if we also show JS examples

**Comment by tlancina** [comment]
Oh whoops I missed the memo on TS for the tutorial: https://github.com/driftyco/ionic-site/commit/f5a7ab69951c53881d26f6a760b6f8236dfe661d

**Comment by tlancina** [comment]
Re-opening because if we're doing TS then the tutorial needs to be updated to show instructions and examples using the TS tutorial.

**Comment by jgw96** [comment]
@tlancina @perrygovier i can help with this! (:

**Comment by tlancina** [comment]
@jgw96 awesome! I think it would be optimal to have tabs to allow both JS and TS examples for things, then people can just choose but we can default to TS.

@perrygovier thoughts?

**Comment by perrygovier** [comment]
We considered it, but @adamdbradley and I met the other day and decided it was low enough of a priority to close the issue. TS all the way!

**Comment by perrygovier** [comment]
See #426

**Comment by jgw96** [comment]
@tlancina @perrygovier Great, ill start going through and changing everything to typescript!

**Comment by jgw96** [comment]
Very glad were going with typescript all the way, its honestly the best language for Angular 2, gets rid of a'lot of boilerplate that you have to have with straight es6.

**Comment by perrygovier** [comment]
I think this can be closed now. Reopen if not
