### ISSUE TITLE
Remove auto `<br>` in doc formating

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#486]
If the source code has a line break, then somewhere along the lines it's changed to a `<br>`. Is it possible to not add the `<br>` and let the text just have a normal HTML flow?

![image](https://cloud.githubusercontent.com/assets/452425/13517442/46277732-e189-11e5-8e44-273c119e22df.png)

**Comment by perrygovier** [comment]
fixed in f757f04f26d860caf4c8e60e5554ca5aea95e651
