### ISSUE TITLE
Ionic 2 cli section typescript

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#489]
The CLI section of the Ionic 2 docs seems to be missing references to how to generate a typescript ionic 2 project. I was not able to find a reference to using --ts like there is in the tutorial in the Getting Started secition.

**Comment by perrygovier** [comment]
Is this still necessary?

**Comment by mhartington** [comment]
Nope, already have a note in there about generating a typescript project.

http://ionicframework.com/docs/v2/getting-started/tutorial/

**Comment by perrygovier** [comment]
swiggity sweet
