### ISSUE TITLE
market place search for ionic2

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#490]
_From @iBasit on March 2, 2016 15:19_

This is a feature request.

There is no way to search for ionic2 themes or plugins.. one have to go through each one and to see if its supported for ionic2. its very bad. can you put filter or tag, so we can look up ionic2 themes or plugins. 

_Copied from original issue: driftyco/ionic#5684_

**Comment by perrygovier** [comment]
We added badges to v2 items and you can now search for v2 and it'll bring up results
