### ISSUE TITLE
Improve documentation for icons

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#493]
We need to add more documentation on using icons, see this e2e test: https://github.com/driftyco/ionic/blob/2.0/ionic/components/icon/test/basic/main.html

Should be here: http://ionicframework.com/docs/v2/components/#icons

**Comment by brandyscarney** [comment]
Also, the button to "Explore the full icon set" links to https://www.ionicons.com but this isn't up to date.

**Comment by jgw96** [comment]
@brandyscarney what would be a better link for the "Explore the full icon set" to go to? This? https://github.com/driftyco/ionicons/tree/3.0

**Comment by brandyscarney** [comment]
@jgw96 I was thinking this link: http://ionicframework.com/docs/v2/resources/ionicons/

**Comment by perrygovier** [comment]
fixed in 781fef4d33fb9c9ae273dfac7386ea4b6e3a6ac6
