### ISSUE TITLE
rootNav is not a function

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#498]
_From @astopo on March 9, 2016 18:19_

#### Short description of the problem:
[NavController documentation](http://ionicframework.com/docs/v2/api/components/nav/NavController/) is confusing. Trying to call `this.nav.rootNav()` on NavController instance throws an error.

```
Uncaught EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: this.nav.rootNav is not a function
ORIGINAL STACKTRACE:
TypeError: this.nav.rootNav is not a function
```

#### What behavior are you expecting?
Expecting `rootNav()` to be a function. It is actually a property.

**Steps to reproduce:**
1. Create a root page, and a tabs page. 
2. In a tab page of the tabs, inject NavController.
3. Try to call rootNav() on the NavController instance of the tab page.

```
export class DashboardPage {
	static get parameters() {
    return [[NavController]];
  }

  constructor(nav) {
    this.nav = nav;
  }

  submitLogout() {
     // Trying to get rootNav here to get out of TabsPage and go to root nav page.
      this.nav.rootNav();
  }
}
```

Got it to work with:

```
export class DashboardPage {
	static get parameters() {
    return [[NavController]];
  }

  constructor(nav) {
    this.nav = nav;
  }

  submitLogout() {
      this.nav.rootNav.push(LoginPage);
  }
}
```
**Ionic Version**: 2.0.0-2beta

**Browser & Operating System**: Chrome

_Copied from original issue: driftyco/ionic#5783_

**Comment by adamdbradley** [comment]
Yeah you're absolutely right. We need to fix up our docs generation to handle this. Thanks

**Comment by mhartington** [comment]
curious on how we should document this. Should this be documented as a method and just provide an example? Curious if you had any inputs on this @astopo?

**Comment by astopo** [comment]
Is there a way to not document it as a method and document it as a property instead? I think a method may be misleading

**Comment by adamdbradley** [comment]
@astopo agreed, it should be documented as a property and not a method. 

@mhartington Can dgeni be updated so it basically doesn't put the `()` at the end of the property?

**Comment by mhartington** [comment]
For sure, it's something we're looking into. 
I think a good option, for any getter that we could have, is to create a new process for them so we can automate it.

**Comment by perrygovier** [comment]
I went with adam's approach, renaming everything to be "Members" instead of methods, and differentiating between methods and properties by the presence of `()`.
