### ISSUE TITLE
docs: Windows Phone documentation

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#500]
_From @ErkoKnoll on March 11, 2016 17:28_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Would be nice to get started with wp platform, but there is no documentation as of yet how to properly set it up.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5812_

**Comment by brandyscarney** [comment]
What kind of docs are you looking for? If you start a new project from the command line it will have windows mode already included. If you have an existing project, you can follow the steps in the changelog to add the windows mode: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#windows-mode

or refer to the conference app commit: https://github.com/driftyco/ionic-conference-app/commit/304e2a49693d411458bc424028e86c7d6966416e

**Comment by brandyscarney** [comment]
_From @ErkoKnoll on March 11, 2016 18:3_

I tried to add a cordova wp support by using "ionic platform add wp" but it didn't recognize the platform. I believe I was using Ionic CLI 2.0.0-beta19 when trying it out. Do I have to use cordova's own platform name which is wp8 or windows?

**Comment by brandyscarney** [comment]
Oh ok! So the platform name for ionic is the same as cordova: `windows`. To run your app on windows you will need a few things first, here is a tutorial for it: https://cordova.apache.org/docs/en/6.x/guide/platforms/win8/index.html

I do agree though that we need to add some documentation on how to build/run your apps on different platforms, so I am going to move this issue to the ionic-site repo. :smile:

**Comment by ErkoKnoll** [comment]
Thanks for the link. But to clarify, do you only support windows 10 or you support wp 8.1 too which is also valid deployment target for "windows" platform? The reason why I ask is that windows 10 supports "Remote Mode" while wp 8.1 supports only "Local Mode" that sets in place certain restrictions such as direct DOM manipulation that Ionic/Angular may rely on.

Quote: "Remote Mode eliminates those requirements, which makes it possible to use unmodified libraries like jQuery or AngularJS directly in your code, without any changes."

**Comment by perrygovier** [comment]
merged, thanks @mhartington!
