### ISSUE TITLE
Improve this doc broken on API pages v2

### ISSUE THREAD

**Issue by jasperkuperus** [driftyco/ionic-site#502]
If you go to the **2.0 API** (http://ionicframework.com/docs/v2/api/) and click on `Improve this doc` for any of the API entries, you'll get a github 404, e.g.:

http://ionicframework.com/docs/v2/api/components/infinite-scroll/InfiniteScroll/

Refers to (404):

https://github.com/driftyco/ionic/edit/2.0//home/ubuntu/ionic/ionic/components/infinite-scroll/infinite-scroll.ts#L2

It seems to work properly outside the API section of the site.

**Comment by perrygovier** [comment]
thanks! fixed
