### ISSUE TITLE
docs: weather aa

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#506]
_From @raushann100 on March 15, 2016 5:27_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>not getting any helpfull documentation</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5841_

**Comment by brandyscarney** [comment]
@raushann100 Could you give us a bit more information? What documentation isn't helpful?

**Comment by perrygovier** [comment]
Gonna close this. @raushann100. Feel free to submit a new issue w/ more info
