### ISSUE TITLE
ionic-toggle ng-true-value and ng-false-value don't work in docs

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#518]
_From @oneillsp96 on September 30, 2015 0:37_

This is not a change to the ionic-toggle directive itself.  However, in the html here: http://ionicframework.com/docs/api/directive/ionToggle/
 you have the following code snippet:

 <ion-toggle toggle-class="toggle-assertive"
                    ng-model="emailNotification"
                    ng-true-value="Subscribed"
                    ng-false-value="Unubscribed">
          Newsletter
        </ion-toggle>

This doesn't work because there are no single quotes on 'Subscribed' and 'Unsubscribed', like this:
ng-true-value="'Subscribed'"

Not a big deal, just had me scratching my head for a few minutes and might be nice to update and keep the docs pretty!  
By the way, I love Ionic....Thanks!

_Copied from original issue: driftyco/ionic#4447_

**Comment by jgw96** [comment]
_From @chiusite on November 19, 2015 17:59_

thanks, onelipse.   i was wondering why it did not work.

btw, you can fix it in github  too

**Comment by jgw96** [comment]
_From @oneillsp96 on November 20, 2015 1:4_

I can only edit the toggle directive itself and submit a pull request for it....it's not an issue with the toggle, just that the way it's being shown (with slightly broken code) could be confusing

**Comment by jgw96** [comment]
Thanks for opening this issue with us! Since this is an issue related to the docs site and not the actual framework i will be moving this issue to that repo. Please feel free to continue the conversation over there! Thanks again!

**Comment by mhartington** [comment]
@oneillsp96  Ahh in the codepen. Noted! 

Should be updated! Thanks for the heads up :smile:
