### ISSUE TITLE
getting started page

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic-site#528]
This is more of a recommendation. 

I used to work with the alpha version and it took me awhile to figure out there is no webpack "stuff" here so I had to npm install everything. I read in the forum that webpack was eliminated from the starter products in order to make it easier for users (whatever that means LOL). I think that could've been nice to know before I started using it. Pretty much some mention in the docs about npm install. 

Also I think it is useful to add, that in order to use (ionic start and not have issues) you have to have python 2 installed, because I had python 2 and 3 and it gave me errors (which I put as an issue and was fixed)

**Comment by mhartington** [comment]
Hey thanks for the suggestions! 

Curious about the python part. I could be mistaken, but I don't believe our CLI requires anything with python. You said you opened an issue? Could you link to it?

**Comment by Bandito11** [comment]
Not ionic CLI but I read node was written Python 2 as well as C++ as it was written in both under the hood. In fact you need Python 2 among other things install to build. 

https://github.com/nodejs/node/blob/master/BUILDING.md

**Comment by mhartington** [comment]
Ahh, in reference to building node from source. For most devs, they'll probably be running the installer from node's site or using some sorts of package manager. With those process, you already have a binary that gets installed so you shouldn't need to have python setup. 

Going to close this for now.
