### ISSUE TITLE
iOS Preview app crash on actionsheet -> alert. 

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#529]
Steps:
1) go to http://ionicframework.com/docs/v2/components/#action-sheets and click on the action sheet button in the ios demo
2) go to http://ionicframework.com/docs/v2/components/#alert and click on the "show basic alert" button

Expected: to show an alert

Instead: nothing

**Comment by drewrygh** [comment]
Related: https://github.com/driftyco/ionic/issues/5968 (both are z-index issues)
