### ISSUE TITLE
Add component docs/demo: loading

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#531]
Add the loading component once beta.4 is released. Refer to the following tests:

https://github.com/driftyco/ionic/tree/2.0/ionic/components/loading/test/

and the API demo:

https://github.com/driftyco/ionic/tree/2.0/demos/loading

**Comment by perrygovier** [comment]
@drew, can you have this demo ready for the beta.4 release? 
@mike, can you have the docs for it ready to go?
