### ISSUE TITLE
docs: update theming docs to include other way to write colors map

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#534]
The theming docs should mention the `color` function to get a color, and the new way to write the `$colors` map. See the beta.4 changelog: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#theming-with-base--contrast-colors---5445

**Comment by mhartington** [comment]
Closed via https://github.com/driftyco/ionic-site/commit/9788f906bbc2c27dfa055db4779cd74489ba7294
