### ISSUE TITLE
looks like learning.ionicframework.com is hosed

### ISSUE THREAD

**Issue by mkobar** [driftyco/ionic-site#536]
looks like learning.ionicframework.com is hosed:

If I try to goto a specific link:  http://learn.ionicframework.com/formulas/data-the-right-way/

the page loads then immediately reverts to http://ionicframework.com/

This also happens even if I try to navigate to http://learn.ionicframework.com/
This looks very recent!

**Comment by mhartington** [comment]
Hi there! Yes, the learn site has long been out of date so we decided to shut the site down. But we've kept the git repo around as a point of reference. 

https://github.com/driftyco/ionic-learn

**Comment by mkobar** [comment]
Mike -

I totally understand but:

The learning site is briefly displayed then it reverts back to the
ionicframework.com main page.  Looks broken, even if it is working as
planned.  I would suggest not showing the learning pages then reverting.

Thanks!

Mike


---
Mike Kobar
RKO Security
http://www.RKOSecurity.com <http://www.rkosecurity.com/>
617 701-6019

**Comment by mlynch** [comment]
@perrygovier is working on this

**Comment by mkobar** [comment]
Thanks for the good news.

Keep rocking it!

---
Mike Kobar
RKO Security
http://www.RKOSecurity.com <http://www.rkosecurity.com/>
617 701-6019
