### ISSUE TITLE
Style the related API links in a list form

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#538]
List, comma separated, or however Ben wants it to make it look more differentiated

![screen shot 2016-04-11 at 3 54 32 pm](https://cloud.githubusercontent.com/assets/6577830/14440479/fc750738-fffd-11e5-9186-3e3ab21856cc.png)

Example at bottom: http://ionicframework.com/docs/v2/api/components/item/ItemSliding/

**Comment by perrygovier** [comment]
fixed in https://github.com/driftyco/ionic/commit/dec9f76105a47850b01faa0e16dd9905f00b095a
