### ISSUE TITLE
Format getContentDimensions return type

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#540]
Fix the return type for `getContentDimensions`
![image](https://cloud.githubusercontent.com/assets/452425/14463031/25576dc6-008f-11e6-9ad6-c77aec281608.png)

http://ionicframework.com/docs/v2/api/components/content/Content/#getContentDimensions

**Comment by perrygovier** [comment]
I'm going to do manual formatting for now. If there's 2 or more cases like this, we can add some new macros to dgeni
