### ISSUE TITLE
Events doc needs clarification for `.publish()`

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#544]
_From @wli on April 12, 2016 21:15_

#### Short description of the problem:
The [Events documentation ](https://github.com/driftyco/ionic/blob/2.0/ionic/util/events.ts#L88) for the `.publish()` implies that the argument signature is `topic:string, eventData:any`. However, in practice, it is actually a variable number of arguments: `topic:string, ...args`.

Right now, event handlers will receive an argument array `args:any[]` instead of the implied single-object `eventData:any`. This should be clarified one way or the other.

**Which Ionic Version?**
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v5.8.0

_Copied from original issue: driftyco/ionic#6142_

**Comment by jgw96** [comment]
Hello! As this is an issue with the docs site instead of the actual framework i will be moving this issue over to that repo. Thanks and feel free to continue the conversation over there!

**Comment by mhartington** [comment]
Hmm, this is a head scratcher. In this case, the event data could be anything. So if we did 

```
event.publish('updated', a,b,c);
```

The `a,b,c` being args could be anything. But if you ran the function, the would get printed out as an array.

But there's nothing saying that the user has to pass an array. Leaving it as `any` will cause the lease confusion in this case. Closing

**Comment by wli** [comment]
@mhartington just want to be clear: if the user passes a single string variable, it will show up as a string array still, instead of (what I expect) to be a string. `args` is always an array, regardless of whether you pass multiple arguments, or just one.

**Comment by mhartington** [comment]
For sure, and I'm not arguing that. What I'm saying is that for the user reading the docs, seeing `any` is a bit easier to understand than `any[]`.

**Comment by wli** [comment]
Okay, sounds good. In that case, I think you'll need to update the example at the top of the page to reflect this. Right now, it's:
```js
// first page (publish an event when a user is created)
function createUser(user) {
  console.log('User created!')
  events.publish('user:created', user);
}

// second page (listen for the user created event)
events.subscribe('user:created', (user) => {
  console.log('Welcome', user);
});
```

But in reality, it's actually this:
```js
// first page (publish an event when a user is created)
function createUser(user) {
  console.log('User created!')
  events.publish('user:created', user);
}

// second page (listen for the user created event)
events.subscribe('user:created', (userEventData) => {
  console.log('Welcome', userEventData[0]);
});
```

**Comment by biesbjerg** [comment]
I'd rather the code was adapted to adhere to the docs than the other way around.

@mhartington: I don't understand the decision to always pass data as an array. Can you maybe elaborate why this choice was made?

**Comment by scunningham777** [comment]
As the OP alludes to, the data always gets passed as an array because [Events.publish()](https://github.com/driftyco/ionic/blob/2.0/ionic/util/events.ts#L90) is using Typescript's ["Rest Parameter"](http://www.typescriptlang.org/docs/handbook/functions.html#rest-parameters) syntax, which always wraps matching arguments in an array, regardless of the number of arguments (including 0). 

IMHO, this seems unnecessary - if the publisher wants to pass multiple values to the subscribers, couldn't they just pass an array, rather than passing the multiple values as separate arguments to `publish()`? The current documentation makes it look like you can only pass two arguments to `publish()` anyway.

**Comment by ChrisEelmaa** [comment]
very confusing.

the docs seem to be out of date: https://ionicframework.com/docs/api/util/Events/

**Comment by piotrowski** [comment]
What exactly @ChrisEelmaa? The issue you are responding to is almost a year old, so a lot has changed since then.
