### ISSUE TITLE
For the virtual scroll docs

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic-site#545]
I noticed that the docs wasn't clear of how to use any of the properties of the [virtualScroll]. All the properties that take a string you pass the value like this [property]=" 'stringValue' " not like this: [property]="stringValue". The docs wasn't clear about that.

Example that I wrote from the forum

When doing this:

```
        <ion-list [virtualScroll]="newArray" [approxItemHeight]="500px" [bufferRatio]="3.1">
            <button  *virtualItem="#item" large>
                ItemName
            </button>
        </ion-list>

```
because the 500px is supposed to be a string you have to write the ' ' inside the " " in other words this will fix it:

```
        <ion-list [virtualScroll]="newArray" [approxItemHeight]=" '500px' " [bufferRatio]="3.1">
            <button  *virtualItem="#item" large>
                ItemName
            </button>
        </ion-list>

```
notice the ' '  inside the " ". 

" '500px' "

**Comment by brandyscarney** [comment]
Adding the brackets is using Angular's [property binding](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#property-binding). When you write `[approxItemHeight]` you are binding an expression to `approxItemHeight`. If you want to just pass a string you would use `approxItemHeight="500px"` without the brackets. Maybe we need to go over property binding better in the docs, but this isn't limited to Virtual Scroll. :smile:

**Comment by Bandito11** [comment]
I agree but that's how it works for me *lol*  

If I dont that all I see its a blank page.

**Comment by mhartington** [comment]
http://learnangular2.com/templates/

This is the basics and angular 2 property binding. 

When we do `[approxItemHeight]="500px"`, angular's internals expect there to be a property of `500px` to bind to. 

If you remove the `[]` and just write `approxItemHeight="500px"`, the property will accept 500px as the value, and not set up and bindings. 

While `[approxItemHeight]="'500px'"` is still valid, it's not how you should be setting the properties value.

**Comment by Bandito11** [comment]
Ok thank you
