### ISSUE TITLE
LocalStorage docs are a bit misleading

### ISSUE THREAD

**Issue by wli** [driftyco/ionic-site#546]
This example on the [LocalStorage](http://ionicframework.com/docs/v2/api/platform/storage/LocalStorage/) docs page has the following example line:
```
this.local.set('didTutorial', true);
```

However, LocalStorage only stores string keys and string values (tested in Chrome 50.0.2661.49).
```
> localStorage
Storage {length: 0}
> localStorage.setItem('foo', true)
undefined
> localStorage.getItem('foo')
"true"
> typeof(localStorage.getItem('foo'))
"string"
```

Thus, if you follow the example, and write the following code:
```
this.local.set('didTutorial', false);
this.local.get('didTutorial').then(val => {
  this.didTutorial = val;
});
```

You would end up with a truthy value for `didTutorial`, which is not intended.
```
> !!"false"
true
```

The docs aren't wrong (you can indeed _store_ any value), but you'll run into trouble reading them out. Please let me know if I'm missing something!

**Comment by mhartington** [comment]
https://youtu.be/hou0lU8WMgo

Will update the example, thanks!

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic/commit/dca6540098ab2473d1f37acdf19ac62c59490c40
