### ISSUE TITLE
Show Color Swatches for theme

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-site#547]
I am looking at the `Theming your Ionic App` [page](http://ionicframework.com/docs/v2/theming/theming-your-app/) to see what colors we provide by default.

I have to open another tab and google the hex codes for this to be meaningful.  Can we show color swatches or something on this page?

**Comment by mhartington** [comment]
We could add this image?

![screen shot 2016-04-15 at 12 34 18 pm](https://cloud.githubusercontent.com/assets/2835826/14568374/82144510-0306-11e6-9dbc-74e848d515a0.png)

Or something similar.  Sadly, code won't recognize this and display the color square next to it.

**Comment by brandyscarney** [comment]
I personally like how Slack does it:

![screen shot 2016-04-15 at 12 38 56 pm](https://cloud.githubusercontent.com/assets/6577830/14568463/15907214-0307-11e6-9465-0922ae61bd5c.png)

but at the same time we want to make sure we emphasize that these are just random colors and they can change them or remove them if they want.

**Comment by brandyscarney** [comment]
On that note...favorite was something I added to the conference app, it shouldn't be in the starters or the theming section.

**Comment by mhartington** [comment]
Thats true. The actual value of the colors don't matter. The focus is making your own color choices. Closing then.
