### ISSUE TITLE
Update ion-slide demos to use `@ViewChild`

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#549]
Instead of `app.getComponent`, use `@ViewChild` to get ahold of the slides to interact with: https://github.com/driftyco/ionic/commit/2295bd9264f3ba8f2ffce7e07fcde1d3fd1ac03a 

Not sure if any of our demos are doing that, but in general we need to replace using `getComponent` with `@ViewChild`.

/cc @drewrygh @jgw96 @brandyscarney @mhartington

**Comment by mhartington** [comment]
Will update.

**Comment by mhartington** [comment]
Most have been updated already.

The last one in question is `ID`, which really goes alone with `getComponent`.

http://ionicframework.com/docs/v2/api/components/app/Id/

This now becomes a question of what do we do with ID?

**Comment by adamdbradley** [comment]
Do not link to it from the left menu for now.

**Comment by mhartington** [comment]
It is decided.

https://github.com/driftyco/ionic/commit/58570f2da5cd9b20739881a7adaf54d316c2902d
