### ISSUE TITLE
Reduce how many times version numbers are said in plunkers

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#551]
In this plunker, I see the ionic's version 3 times, but only 1 of them is right: http://plnkr.co/edit/OBQjWnCgVkf7Z7mXezBs?p=preview

To reduce having to remember all the places the version number needs to be updated, only have it listed in the script tags, not in content, header or plunker description.

**Comment by jgw96** [comment]
Fixed by the above commit (:

**Comment by jgw96** [comment]
fixed by the above commit (:
