### ISSUE TITLE
Document IONIC_DIRECTIVES and ionicProviders()

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#552]
Explain what `IONIC_DIRECTIVES` and `ionicProviders()` are, and how to import them. Also show an example of bootstrapping an app without using `@App`.

https://github.com/driftyco/ionic/issues/6078#issuecomment-208324539

**Comment by mhartington** [comment]
Added and documented via https://github.com/driftyco/ionic/commit/902fbd0f62109b6fd0841cf6e1b4b90ea39a75cb

**Comment by mhartington** [comment]
Not saying that this is final...we can review it and change wording/format

**Comment by omeid** [comment]
As long as exposed API ins't going to change, it should be good!

Thanks for the great work guys!
