### ISSUE TITLE
Put NavController lifecycle events in a table

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#553]
http://ionicframework.com/docs/v2/api/components/nav/NavController/

**Comment by mhartington** [comment]
![screen shot 2016-04-19 at 9 22 24 am](https://cloud.githubusercontent.com/assets/2835826/14640599/4358cc80-0610-11e6-8239-211ab70089da.png)

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic/commit/28eb819a0e1e2a29f56c11b8c21bae7c5eb27bd7
