### ISSUE TITLE
Automatically create link id's from markdown headers

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#554]
Instead of manually writing `<h2 id="creating_pages">Page creation</h2>`, allow the markdown to just have `## Page creation`, which automatically generates `<h2 id="page-creation">Page creation</h2>`.

https://github.com/driftyco/ionic/blob/b282e90e2cbb74559aab79eee8443a4d7c85502a/ionic/components/nav/nav-controller.ts#L61

**Comment by mhartington** [comment]
Pretty sure NavController was the only place this appeared. Fixed.
