### ISSUE TITLE
Windows Phone image has a border?

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-site#565]
Why does the Windows Phone image have a border around the device? Android and iOS do not. Looks weird. 

![capture](https://cloud.githubusercontent.com/assets/2852839/14731972/42fed278-0856-11e6-83c7-8bdf7a333ac3.PNG)

**Comment by mhartington** [comment]
That is actually the white of the windows phone device

![[](http://cdn.slashgear.com/wp-content/uploads/2016/01/lumia-1520-820x420.jpg](http://cdn.slashgear.com/wp-content/uploads/2016/01/lumia-1520-820x420.jpg)
