### ISSUE TITLE
Update Plunkr to beta 6

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-site#566]
Can the default ionic 2 plunkr be updated to beta 6? Currently on beta 5.

**Comment by jgw96** [comment]
@dylanvdmerwe will update that this morning, thanks for the heads up

**Comment by jgw96** [comment]
@dylanvdmerwe Hey, so just updated the issue template and heres the link to the updated plunker: http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview
