### ISSUE TITLE
Note about ion-img in virtualscroll docs

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#581]
We should probably put a note in the virtualscroll docs about ion-img only being used with virtualscroll. There have been a few users (https://github.com/driftyco/ionic/issues/6257) trying to use it outside of virtualscroll which does not work at this moment, and is not intended to work as ion-img is only intended to work with virtualscroll.

**Comment by mlynch** [comment]
I'm concerned this isn't the best solution. Even with the docs, it's so natural to want to write `ion-img` once you get a taste for it.

Instead, could we tweak the `Img` component to work like a standard `img` for all non-virtual scrolling cases?

**Comment by jgw96** [comment]
Im sure we could, might be something to ask @adamdbradley about? I was suggesting adding this to the docs in the meantime until a better solution was found so that way we potentially cut down on at least a small amount of confusion, but if it was fixed soon then it probably wouldn't be worth adding to the docs.

**Comment by perrygovier** [comment]
I think saying one thing and then saying something different might lead to even more confusion. Max's suggestion seems like the right approach. We can explain in driftyco/ionic#6257 that it's coming soon, so when people go to post an issue it shows up.

**Comment by mlynch** [comment]
@perrygovier I like that idea. I think it also touches on something we've done with the rest of the framework, if something *has* to be a child of something else, it's usually prefixed as such. Something generic like `ion-img` seems like it could/should be used anywhere an img would have been used and so I don't think we should bind it to virtual scrolling. Also it leaves room for us to do fun img stuff throughout an app in the future

**Comment by perrygovier** [comment]
Ooh, like service worker auto-scaled DPI appropriate images in a `<picture>` element, or auto open:graph meta tags. Ok, maybe that's overkill, but yeah, flexibility ftw. Closing this here then.
