### ISSUE TITLE
docs: Wrong information about the logo-* Ionicons

### ISSUE THREAD

**Issue by iignatov** [driftyco/ionic-site#583]
The instructions for the `logo-*` icons _(e.g. `logo-javascript`)_ on the [Ionicons docs page](http://ionicframework.com/docs/v2/ionicons/) are incorrect.

Currently the usage instructions _(e.g. for `logo-javascript`)_ are:
```html
  <!--Basic: auto-select the icon based on the platform -->
  <ion-icon name="javascript"></ion-icon>

  <!-- Advanced: explicity set the icon for each platform -->
  <ion-icon ios="logo-javascript" md="logo-javascript"></ion-icon>
```
but instead they should be:
```html
  <!--Basic: auto-select the icon based on the platform -->
  <ion-icon name="logo-javascript"></ion-icon>

  <!-- Advanced: explicity set the icon for each platform -->
  <ion-icon ios="logo-javascript" md="logo-javascript"></ion-icon>
```
or even better _(because the name is the same for all platforms)_:
```html
  <ion-icon name="logo-javascript"></ion-icon>
```

The title should also display the full icon name, i.e. `logo-javascript` instead of `javascript` _(currently)_.

Additionally it would be great if these icons _(i.e. `logo-*`)_ are displayed in all columns in the table view, because currently it looks as if they are available only for iOS.

Here is a related forum topic: https://forum.ionicframework.com/t/freebsd-devil-bug/50597

**Comment by mhartington** [comment]
Looks like the actual template for the modal may need to change
