### ISSUE TITLE
Document the need for "enough" data for InfiniteScroll

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-site#584]
When using InfiniteScroll, if you do not have enough data to fill the view port, then you can't get InfiniteScroll to fire because you never get a chance to scroll. The documentation should mention this and suggest people ensure that their initial dataset includes enough data to fill up the view port on most devices. Obviously we can't provide a firm number ("20"), but a warning will ensure folks think about this and plan for it.

**Comment by mhartington** [comment]
Going to close this. We're going to call this a bug and make sure it's fixed instead.

**Comment by victorlenz** [comment]
I am still facing this issue. I am using ionic-angular 5.0
