### ISSUE TITLE
docs: add windows mode defaults to the config API docs

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#585]
http://ionicframework.com/docs/v2/api/config/Config/

**Comment by brandyscarney** [comment]
I updated the docs but with the additional row it is a little squeezed:

![screen shot 2016-04-28 at 4 56 36 pm](https://cloud.githubusercontent.com/assets/6577830/14901189/3abf79a8-0d62-11e6-9579-4429e2c81200.png)

Perry is thinking we move this to a separate doc, maybe one that goes over the modes more in detail and then link to it from config?

**Comment by mhartington** [comment]
I like the idea. That does seem a bit tight

**Comment by brandyscarney** [comment]
Another idea - what if the config API docs had just the property name & a description of the property, but the theming section documented the mode defaults?

**Comment by perrygovier** [comment]
I like that idea. Make it so.
