### ISSUE TITLE
Remove use of app.getComponent and id attributes

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#586]
Redo the demo's so they use `@ViewChild` instead of `app.getComponent()`. Also remove the `id` attributes from `ion-nav`.

**Comment by adamdbradley** [comment]
This will be required for the beta7 update.

**Comment by mhartington** [comment]
Unless I missed anything, this should already be taken care of. I vote we also remove the `id` directory from ionic-site as well.

**Comment by mhartington** [comment]
Missed in in Tabs. But other than that, we're good.
