### ISSUE TITLE
dynamic templates in ionic 2

### ISSUE THREAD

**Issue by vonovak** [driftyco/ionic-site#592]
Hello!
I was just playing with ionic 2 and wanted to use the [dynamic templates](http://ionicframework.com/docs/platform-customization/dynamic-templates.html) as described in ionic 1 docs. 
I assume that the `@App` decorator is the place where I should change the `templateUrl` in ionic 2, but I couldn't get it working.

It [seems](https://github.com/driftyco/ionic/blob/2.0/ionic/decorators/app.ts) the `@App` decorator expects a string and therefore a function wouldn't work. I attempted to get around it by IIFE that would return a string immediately but it doesn't seem I can access the Platform.

This probably isn't a typical scenario but I was just wondering if such thing was possible. Would be nice to document it, too.

**Comment by mhartington** [comment]
Hey there!  So this kind of thing is not supported with Angular 2. Instead you should be changing the template itself instead.
