### ISSUE TITLE
docs(Loading): Making it clear that after dismissing a loading component you cannot reuse it

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#597]
Once you dismiss a Loading component that you have created you cannot simply reopen that same instance of the component. Here is a use case from a user that demonstrates not being able use an instance of the Loading component twice: http://plnkr.co/edit/LY1wi7fh5AxeRNoDzOan?p=preview. In my view this is the correct behavior of the Loading component, but should probably be included in the Loading docs.

**Comment by mhartington** [comment]
This really has to do more with how the loading component is declared in the users code.

http://plnkr.co/edit/d1eY0OQ2XVV6a9YDyh91?p=preview

**Comment by jgw96** [comment]
Yep, your exactly right. You have to create a new instance of the loading component each time you want to use it as it gets "destroyed" on dismiss(). In my opinion this should be included in the docs though as right now it looks like you could simply create one instance of the component and continue to reuse it. You can see more info about the user's use case in the above linked issue.

**Comment by lricoy** [comment]
I have downloaded and started adding to the documentation after getting the replies from the original issue. If this is OK I will send a PR later today.

**Comment by mhartington** [comment]
added via https://github.com/driftyco/ionic/commit/40329314ae8853ef680779889b6b07d9d7adcc35
