### ISSUE TITLE
Create Resources Landing Page

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#603]
Right now the "Resources" link just expands and shows all the resource links. However, we're planning on explaining and adding more articles to this list, so it probably won't scale well.

![image](https://cloud.githubusercontent.com/assets/452425/15253336/6c675fe8-18f7-11e6-9403-cb8b6f1b98e0.png)

Instead, let's have a resources landing page where we can group similar content and links and make it easier to looking through articles that can help commonly asked questions. From there, commonly asked questions found in forum posts and issues created can be answered with a link to an article in the resources section, and others reading the forum/issues will have a good centralized area. Additionally, if our suggestion and code changes over time, then we're not hardcoding stale code in issues and posts, but rather make it easy to update our suggestions in the articles.

cc @mhartington @jgw96

**Comment by jgw96** [comment]
cc @perrygovier

**Comment by perrygovier** [comment]
@bensperry, we talked about this a while ago, can you whip up a design?

**Comment by bensperry** [comment]
Yeah, I can definitely do that. @adamdbradley do you have any examples of this being done well elsewhere that I can reference?

**Comment by jgw96** [comment]
@bensperry not sure if this is really helpful, but heres how polymer does it: https://www.polymer-project.org/1.0/articles/

**Comment by perrygovier** [comment]
Adam and I were just talking and that's kinda the structure that came up. Ben we could maybe combine what you had in mind, a list of "card" like on ionic.io/discover, but then having an condensed list of items below it for topics/links that don't have their own card. 

The section is kind of that drawer in your kitchen where all the random things that you don't have a place for go. Just a place to put things quick that doesn't fit the other categories well.

**Comment by perrygovier** [comment]
Another good example @brandyscarney mentioned in slack https://design.google.com/resources/

**Comment by adamdbradley** [comment]
- Design: @bensperry 
- HTML/Template Creation: @perrygovier 
- Managing which articles to create: @mhartington 
- Generating content: @mhartington @jgw96 
- Proof reading: @kgindervogel @brandyscarney @adamdbradley

Polymer's articles is a good example a the concept, but its design should come from @bensperry: https://www.polymer-project.org/1.0/articles/

**Comment by perrygovier** [comment]
@mhartington, the page is created and live (but not linked). Can you add content?

**Comment by mhartington** [comment]
Initial pass is done. @kgindervogel will take a look and proof read.

**Comment by kgindervogel** [comment]
content looks good and is proofread, too.

**Comment by mhartington** [comment]
This has been done for a while now. 🎉
