### ISSUE TITLE
{{}} wrapped elements not displaying correctly

### ISSUE THREAD

**Issue by chrisgriffith** [driftyco/ionic-site#605]
Throughout the documentation for v2, any {{}} wrapped item is not being shown.
For example, this is what is shown for ion-item
<ion-list>

  // default item
  <ion-item>
    
  </ion-item>

</ion-list>

but if you inspect the comment's in the https://github.com/driftyco/ionic/blob/2.0/ionic/components/item/item.ts that generates the actual documentation, there is a reference to {{item.title}} which is not rendered.

* <ion-list>
 *
 *   // default item
 *   <ion-item>
 *     {{item.title}}
 *   </ion-item>
 *
 * </ion-list>

**Comment by brandyscarney** [comment]
Closed by https://github.com/driftyco/ionic/pull/6584, thanks!
