### ISSUE TITLE
Links to Cordova docs need an update

### ISSUE THREAD

**Issue by nikhilkh** [driftyco/ionic-site#611]
I am one of the Cordova committers and [Cordova docs have been refreshed](https://cordova.apache.org/announcements/2016/03/03/docs-improvement.html) significantly and the links from ionic website need an update:
https://github.com/driftyco/ionic-site/search?p=1&q=%22cordova.apache.org%2F%22&type=Code&utf8=%E2%9C%93

Our GA data shows that Ionic referrals are landing people onto older version of the docs which is often not accurate. Here are my recommendations:
- Always reference "latest" version of the docs - For example, https://cordova.apache.org/docs/en/latest/guide/overview/index.html. There is almost no reason to reference only a specific version of the links.
- Use anchor references as appropriate. We have changed our anchor scheme recently but do not expect that to change in the future. For example, to reference the build command: https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#cordova-build-command
- Plugin docs are now published on the website and should ideally be referenced instead of the github links. For example, here: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/index.html

Please let me know if you have any questions.

**Comment by mhartington** [comment]
Thanks @nikhilkh , will get these updated!

**Comment by mhartington** [comment]
Should be all taken care of now.
