### ISSUE TITLE
docs: Update getting started to specify node/npm versions

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#612]
We need to add that we recommend using Node 5.x with Ionic and npm 3.x somewhere. There are too many issues with old Node/npm versions and even Node 6.x so we should add a note that these versions work best with Ionic (and keep it updated when this changes).

https://nodejs.org/en/download/releases/
https://nodejs.org/dist/latest-v5.x/

**Comment by mhartington** [comment]
It is done.
