### ISSUE TITLE
docs: improve theming documentation

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#613]
So I don't know the best way this can be achieved, but it would be good to improve the documentation behind which Sass variables control what.

A great recommendation by @alexbainbridge: 

> Would be great to have some component "screenshots" with arrows pointing to aspects that different scss values control. With a number of elements taking scss from different components, this would make it easier to know what controls what. i.e. pretty much what you have done above.

I'm not sure how maintaining this would be, but it is something to think about. Please add any thoughts on this here! cc @adamdbradley @mhartington @jgw96 @danbucholtz

**Comment by mhartington** [comment]
Idea: create a dgeni process that can parse comments in scss files. 

```

// Action Sheet
// --------------------------------------------------

// @description action-sheets default width
$action-sheet-width:                             100% !default;
// @description action-sheets maximum width
$action-sheet-max-width:                         500px !default;
```

We already have dgeni documenting APIs, seems fitting that it would do scss too.

**Comment by alexbainbridge** [comment]
Thanks Brandy! 

While I defer to yourselves, even if this was manual, if errors crept in, I am sure the community would correct, hence either manual or automated would provide sufficiently useful, accurate, information and be appreciated by the wider users

**Comment by brandyscarney** [comment]
Another idea is to do something similar to Foundation's [Customize With Sass](http://foundation.zurb.com/sites/docs/v/5.5.3/components/buttons.html#customize-with-sass) sections where it lists the variables related to each component and what they do.

**Comment by brandyscarney** [comment]
Also need to clarify that a `base` and `contrast` must be added to the `$colors` map: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#theming-with-base--contrast-colors---5445

**Comment by perrygovier** [comment]
Brandy and I just chatted about this. 

I'd like to add an new set of documentation attributes. Something like `@styleFile` or `@mdStyles`. Then a dgeni processor can load those SCSS files and get the necessary descriptions and data. We can use a lib like https://github.com/SassDoc/sassdoc if we need help getting data out of the file. 

With the data, we can generate a new section in the applicable components.

**Comment by mhartington** [comment]
@perrygovier this is great. 

![](http://vignette3.wikia.nocookie.net/degrassi/images/f/f5/Tim-gunn-make-it-work.gif/revision/latest?cb=20150117024803)

**Comment by brandyscarney** [comment]
Do you think we could just have one attribute like `@styles` and then use that URL but append the mode to get the other files? I'm just thinking if we add another mode in the future (not planned but you never know) we'll have to manually go through each component and add it.

**Comment by perrygovier** [comment]
I need to verify, but if your naming is consistent everywhere, we can just check to see if the files exist and not need any new attribute at all.

**Comment by brandyscarney** [comment]
Generally it is like the following (using [range](https://github.com/driftyco/ionic/tree/master/src/components/range) as an example):

```
range.scss
range.ios.scss
range.md.scss
range.wp.scss
```

but there are cases where there is just the `component.scss` file (e.g. [refresher](https://github.com/driftyco/ionic/tree/master/src/components/refresher)), or there is no `component.scss` file and only the mode specific ones (.e.g. [radio](https://github.com/driftyco/ionic/tree/master/src/components/radio)).

**Comment by brandyscarney** [comment]
I started adding documentation for the sass variables (see [tabs.ios](https://github.com/driftyco/ionic/blob/master/src/components/tabs/tabs.ios.scss) for example) so I'll just start adding them as I make changes and then when you guys let me know how we should link these to the API I can add that. I'm thinking we have a Sass Variables section, similar to how input properties is set up, that shows which variables affect all modes (if `*.scss` exists) and then a toggle for the different modes `ios`, `md`, and `wp` (if those exist).

**Comment by brandyscarney** [comment]
I've been discussing this with @briandennis. The syntax will look like the following:

```
/// @prop Padding on the tab button
$tabs-md-tab-padding:                  8px 0 10px 0 !default;
```

and that will automatically add the name, default, and description of the variable to the API docs. The tabs component has this added now: https://github.com/driftyco/ionic/commit/b7c45482c6dd87fa48ca1e9034b3c84253a9c3bd

I want to go through issue https://github.com/driftyco/ionic/issues/5651 as part of this issue.

**Comment by briandennis** [comment]
Support for the syntax @brandyscarney described has been added with driftyco/ionic@d5da8ab0e262b099ad2a28afa06ef228a8d7d589

**Comment by brandyscarney** [comment]
Yay! Now we just need to update all of the Sass files (nbd). :smile:

http://ionic-site-staging.herokuapp.com/docs/v2/nightly/api/components/tabs/Tabs/#sass-variables

![screen shot 2016-08-04 at 5 23 28 pm](https://cloud.githubusercontent.com/assets/6577830/17418768/347095c0-5a68-11e6-8b42-278cb8ca5340.png)

Great job Brian! :tada:

**Comment by mhartington** [comment]
![](https://i.imgur.com/7UE8q3Z.jpg)

**Comment by brandyscarney** [comment]
:tada: :tada: :tada:

**Comment by briandennis** [comment]
Keeping the issue open until all of the variables have been converted over
