### ISSUE TITLE
docs: input clearInput attribute example missing

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-site#618]
On [this ](http://ionicframework.com/docs/v2/api/components/input/Input/)page the `clearInput` attribute is listed in the example but does not reflect in the demo. 

May also want to detail how this attribute works. Does the user need to implement the clear function? Is there an event?

**Comment by brandyscarney** [comment]
Thanks for the issue! I'll look into adding this with this issue: https://github.com/driftyco/ionic/issues/6514

**Comment by brandyscarney** [comment]
I updated the docs for this. It should be updated on the site soon. Thanks! :smile:
