### ISSUE TITLE
Popover: add component docs/demos

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#626]
We should add component docs/demos when Popover is released. Blocked by https://github.com/driftyco/ionic/issues/5420

- [x] Component Docs
- [x] Component Demo
- [x] Theming Default Mode Configuration (http://ionicframework.com/docs/v2/theming/platform-specific-styles/)
 - Defaults will be here: https://github.com/driftyco/ionic/blob/2.0/src/config/modes.ts

**Comment by brandyscarney** [comment]
Added the demo on the beta 8 branch in the preview-app: https://github.com/driftyco/ionic-preview-app/tree/feature/beta-8

**Comment by mhartington** [comment]
Component docs added.

**Comment by mhartington** [comment]
It is done. 
https://github.com/driftyco/ionic-site/commit/f8973d380e02502d7aacffac61fc2f25ba704ae3
