### ISSUE TITLE
The navPush binding doesn't seem to work in ts ?

### ISSUE THREAD

**Issue by mmazloum** [driftyco/ionic-site#627]
this code : 
`<button grey [navPush]="pushPage">
      Liste
      <ion-icon name="ios-list-outline"></ion-icon>
    </button> `

Throws this error in the console : 
![image](https://cloud.githubusercontent.com/assets/3626499/15576310/880e52be-2357-11e6-9e02-0cad2ca4c1c8.png)

If replaced with a this.nav.push(...) everything works fine.

Which will be the right way to implement when Ionic 2 will be in release mode (in Typescript ;-))?

How ever thanks a lot for your awesome framework.

**Comment by mhartington** [comment]
What does your template/class look like?

**Comment by mmazloum** [comment]
The buggy code is in the end of the html template, (and I'm quite new to ionic)
this is the html : 
`<ion-navbar *navbar primary>
  <button menuToggle>
    <ion-icon name="menu"></ion-icon>
  </button>
  <ion-title>Lieux disponible</ion-title>
  <ion-buttons end>
    <button secondary solid (click)="presentConfirm()">
      Valider
    </button>
  </ion-buttons>

</ion-navbar>

<ion-toolbar>
  <ion-searchbar></ion-searchbar>
</ion-toolbar>

<ion-content class="map">



</ion-content>

<ion-toolbar position="bottom">
  <ion-buttons>
    <button primary>
      <ion-icon name="ios-navigate-outline"></ion-icon>
    </button>
    <button primary>
      <ion-icon name="ios-home-outline"></ion-icon>
    </button>
  </ion-buttons>
  <ion-buttons end>
    <button grey (click)="switchList()">
      Liste
      <ion-icon name="ios-list-outline"></ion-icon>
    </button>
    
  </ion-buttons>
</ion-toolbar>`

this is the class : 
`import {Page, NavController, Alert} from 'ionic-angular';
import {ListPage} from '../list/list';

@Page({
  templateUrl: 'build/pages/map/map.html',
  providers: [ListPage]
})
export class MapPage {
  private nav: NavController = null;
  private pushPage: ListPage = null;

  constructor(_nav: NavController, _listPage: ListPage) {
    this.nav = _nav;
    this.pushPage = _listPage;
  }

  presentAlert() {
    let alert = Alert.create({
      title: 'Low battery',
      subTitle: '10% of battery remaining',
      buttons: ['Dismiss']
    });
    this.nav.present(alert);
    console.log('test');
  }

  presentConfirm() {
    let alert = Alert.create({
      title: 'Choisir une autre adresse de retour',
      buttons: [
        {
          text: 'Non',
          role: 'cancel',
          handler: () => {
            console.log('Fin');
          }
        },
        {
          text: 'Oui',
          handler: () => {
            console.log('Autre retour');
          }
        }
      ]
    });
    this.nav.present(alert);
  }

  switchList() {
    console.log ("in switch");
    this.nav.push(ListPage, {});
  }

}`

**Comment by mhartington** [comment]
So it's a little off.

`[navPush]` expects there to be a property on your class to bind to.

So a correct example would be.


```
<button grey [navPush]="myPage">
```


```
export class MyClass {
  myPage = ListPage;
}
```

Since you've used the `[]` bindings, it needs to point to a property.

**Comment by mmazloum** [comment]
I had one called pushPage that was initialized with a ListPage type but doing your way worked perfectly, thanks !
