### ISSUE TITLE
Password resets for Ionic.io

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-site#629]
This may not be the best repo.

Twice this morning someone reset my password for ionic.io. I think the system should *not* reset until after an email is sent to the user and the user clicks to complete the process.

**Comment by perrygovier** [comment]
@ericb, thoughts?

**Comment by ericb** [comment]
Is this for apps.ionic.io, or the ionic platform users reset?

**Comment by cfjedimaster** [comment]
Dang it - I'm sorry. It's the platform thing - and most likely someone using my demo. I ran into this before and was confused. Sorry. 

Although in my defense, I filed an ER to make that text customizable so the user would be real clear *who* was asking for resets. :)
