### ISSUE TITLE
Splash Screen Photoshop Template Missing iPad Pro Sizes

### ISSUE THREAD

**Issue by davecardwell** [driftyco/ionic-site#630]
driftyco/ionic-app-lib/pull/88 added new splash resource sizes for iPad Pro, however they are skipped when using the [Photoshop template](http://code.ionicframework.com/resources/splash.psd) on http://ionicframework.com/docs/cli/icon-splashscreen.html because the PSD is “too small”.

`ionic resources --splash` output:
```
splash ios Default-Landscape@~ipadpro.png (2732x2048) skipped, source image splash.psd (2208x2208) too small
splash ios Default-Portrait@~ipadpro.png (2048x2732) skipped, source image splash.psd (2208x2208) too small
```

**Comment by mhartington** [comment]
@bensperry would you be able to bump that up to  `2732x2732`?

**Comment by bensperry** [comment]
Yep!

**Comment by perrygovier** [comment]
Hey @ben, I think there's some confusion, can we get this `splash.psd` adjusted for the new max size? 
https://github.com/driftyco/ionic-code/tree/gh-pages/resources

**Comment by mhartington** [comment]
All Set!
