### ISSUE TITLE
Menu example has small bug w/ Friends

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-site#650]
When trying the Menu demo (http://ionicframework.com/docs/v2/components/#menus), if you select Events and close the menu, the hamburger icon will reopen the menu. If you select Friends, the hamburger menu doesn't work. That means you have to reload the page to keep testing the demo.

**Comment by cfjedimaster** [comment]
Seems to impact iOS and Android demos.

**Comment by cfjedimaster** [comment]
Oh and Windows too. :)

**Comment by brandyscarney** [comment]
Thanks for the issue. :) This is fixed in the preview app and we'll publish it live on the site soon!
