### ISSUE TITLE
Toast position not working

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic-site#654]
Not working here:
http://ionicframework.com/docs/v2/components/#toast

But working here:
http://ionicframework.com/docs/v2/api/components/toast/Toast/

**Comment by brandyscarney** [comment]
I believe this was because the preview app wasn't updated to beta 9 yet. Updating to beta 10 fixed it and it will be live on the site soon, thanks! https://github.com/driftyco/ionic-preview-app/commit/40235164950e35dfc5aa52607d285cbe9f4aaea5
