### ISSUE TITLE
docs: FAQ still uses App & Page decorators

### ISSUE THREAD

**Issue by eddhannay** [driftyco/ionic-site#655]
The App & Page decorators were removed in [beta 8](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-beta8-2016-06-06), but the [FAQ](https://github.com/driftyco/ionic-site/blob/master/docs/v2/faq/index.md) still uses them. These should be removed.

I'm happy to create a PR for this if it's not currently being worked on.

**Comment by mhartington** [comment]
Thanks for the heads up!
