### ISSUE TITLE
npm packages

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic-site#656]
I think it would be a good idea to have an article pertainining the latest npm packages so that users can fix as needed.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind explaining this a little more? Is this resource article what your talking about? http://ionicframework.com/docs/v2/resources/using-npm/

**Comment by Bandito11** [comment]
[https://angular.io/docs/ts/latest/guide/npm-packages.html](https://angular.io/docs/ts/latest/guide/npm-packages.html)


Angular people have what the package.json is supposed to look like. I think it would be wise to have the package.json for ionic updated on the site too, so that the users know what minimum package and the correct version they suppose to have. 


For example I wasted time figuring out that Angular team updated their npm packages. 


Like I said beforehand it is just a suggestion

**Comment by jgw96** [comment]
closing with https://github.com/driftyco/ionic-site/commit/a3f3b6365ee63bbcf4a9a7b51122afd348ca6f69. Thanks for the awesome suggestion @Bandito11 !
