### ISSUE TITLE
docs about ion-toolbar always being first child on page

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#660]
We should add a note to the toolbar docs about the toolbar always needing to be the first child on a page. Related issue: https://github.com/driftyco/ionic/issues/6392

**Comment by brandyscarney** [comment]
This is actually going to change with the next release since we're wrapping them in `ion-header`'s. Also, the `ion-content` can be the first-child as well if there is no toolbar/header.

**Comment by brandyscarney** [comment]
We need to add documentation that a page should only have the following direct children:

```
<ion-header/>
<ion-content/>
<ion-footer/>
```

**Comment by mhartington** [comment]
This could be a good place for a general view component section in the component docs

Go over the anatomy of a view component and such. 
Actually would this be a good fit for the component docs or the getting started guide?

**Comment by brandyscarney** [comment]
Related issues: https://github.com/driftyco/ionic-site/issues/685 https://github.com/driftyco/ionic-site/issues/676

**Comment by mhartington** [comment]
waiting on this before moving forward. https://github.com/driftyco/ionic-site/pull/700

**Comment by mhartington** [comment]
Right now we have it noted in http://ionicframework.com/docs/v2/components/#toolbar
