### ISSUE TITLE
docs: search isn't returning results for things listed

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#662]
I tried searching for `Virtual Scroll` and `VirtualScroll` and the search doesn't list any results in the header. Also, searching for `loading` returns results like ActionSheet, but not loading. Probably a few new components missing.

**Comment by perrygovier** [comment]
I suspect the index isn't generating. Will look in to it

**Comment by perrygovier** [comment]
fixed in fd28683b25c2b63cd5ee6e16b207a32054edb689

**Comment by perrygovier** [comment]
Note, this doesn't currently commit the updated index back to the repo.

Low priority ToDo
