### ISSUE TITLE
docs: supported platforms

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#671]
We should create a resource document that lists the browsers and devices we support. This will make it easier for people to see what we support.

Something like `Supported Platforms` under Resources.

**Comment by adamdbradley** [comment]
http://ionicframework.com/docs/overview/#browser-support

Android 4.1 and above using Crosswalk on Cordova, or Android 4.4 and above without crosswalk.

iOS 7 and above.
