### ISSUE TITLE
menu with header (beta10)

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#676]
_From @movrack on June 30, 2016 8:30_

Since beta  10, my menu have some view problem. Middle down part of it is empty.

In breaking changes I see we must insert toolbar inside header/footer or content.
But, it's not updated in doc for menus. (toolbar is always outside ion-content tag)
http://ionicframework.com/docs/v2/components/#menus

How we should use menus and toolbar in menu ?

_Copied from original issue: driftyco/ionic#7138_

**Comment by brandyscarney** [comment]
_From @imjohnbo on June 30, 2016 13:58_

The toolbar should also be inside a header. Check out Step 3 of Steps to Upgrade to Beta 10, and this quote from the [Changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#breaking-changes):

> The only elements that should be children of a page are ion-header, ion-content, and ion-footer

It normally takes a couple of days for the doc to reflect changes from a new beta release.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to move this to the `ionic-site` repo to make sure the docs are updated for this. :smile:

To answer your question: The menu toolbar should be similar to a page where the `ion-toolbar` is inside of an `ion-header` or `ion-footer`.

**Comment by mhartington** [comment]
Right now we have it noted in http://ionicframework.com/docs/v2/components/#toolbar
