### ISSUE TITLE
Latest "stable" version should be the default one

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic-site#680]
We have several issues in `driftyco/ionic` telling that something is not working because in fact they are reading the documentation of the nightly version (default).

I think it is a much safer option to consider the latest version the default one.

For example this one: https://github.com/driftyco/ionic/issues/7166#issuecomment-230109407
That required a considerable amount of time.

**Comment by brandyscarney** [comment]
Closing in favor of https://github.com/driftyco/ionic-site/issues/692 since that one is assigned to someone.
