### ISSUE TITLE
Wrong modal opacity on app.md.css

### ISSUE THREAD

**Issue by zefrench** [driftyco/ionic-site#690]
Hi,
The opacity of the modal on Android is .01.
So, the modal is totally transparent.

To fix it go to line 6736 of the file build/css/app.md.css
and replace the opacity '.01'  by '1'

**Comment by brandyscarney** [comment]
I don't understand this issue. Which modal is transparent? Is this an Ionic app or is this somewhere in the documentation? Thanks!

**Comment by zefrench** [comment]
There is a error in the file build/css/app.md.css
The line 6736 says the modal has .01 opacity, so if you test a modal in the ionic app 2 beta 10, the modal will be transparent.

**Comment by brandyscarney** [comment]
The opacity is added to the element when it animates open. I'm not seeing any issues with the modal transparency on the conference app: https://github.com/driftyco/ionic-conference-app

Do you have a plunker or github repo where we can reproduce this?

**Comment by zefrench** [comment]
No I don't but on the app I'm develop under this new beta I got the problem.
So I changed it directly in the app.md.scss file on the theming folder.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#7475
