### ISSUE TITLE
feat: [Feat] Add ion-datetime form validation classes

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#693]
_From @Luchillo on July 11, 2016 19:44_

**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently any input receives some clases in function of it's state, the most clear example is `ng-valid` and `ng-invalid`, however the `ion-datetime` component doesn't apply those type of classes on itself.

To provide the user with better output depending on validation state we need those classes.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#7270_

**Comment by brandyscarney** [comment]
Wrong issue moved. :derp:

**Comment by firmankaukabahahmad** [comment]
ok
