### ISSUE TITLE
LocalStorage value types

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#702]
_From @hdsnet on July 14, 2016 11:19_

#### Short description of the problem:
`LocalStorage` lets you set a Boolean value to a given key (even though the only supported type is a string according to the documentation) and when you retrieve such a value it is converted into string. I guess this is intended but if that's the case at least it should be documented because it's very, very confusing. I am ashamed to admit it but it took me an hour to debug this behaviour after quickly prototyping a few hundred lines of code.
```javascript
let local: Storage = new Storage(LocalStorage);
local.set('someKey', true);
local.get('someKey').then((value) => {
    if (value == "true") {
        // Do something if it's true
    }
})
```

_Copied from original issue: driftyco/ionic#7313_

**Comment by mhartington** [comment]
Fixed! 🎉
