### ISSUE TITLE
Links to Github bronken

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#704]
_From @chroda on July 14, 2016 19:43_

First of all, sorry if is a duplicate issue.

I dont know if you guys have another documentation for Ionic1 but I'm still consullting in http://ionicframework.com/

And the link to see the source are broken, can you tell if have another documentation with all working?

_Copied from original issue: driftyco/ionic#7320_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is an issue with the ionic docs and not the ionic framework I will be moving this issue to that repo. Thanks for using Ionic!

**Comment by brandyscarney** [comment]
Just to add more information, the "View Source" links are broken on the JavaScript docs: http://ionicframework.com/docs/api/service/$ionicActionSheet/

@chroda if you change `master` to `1.x` in the URL you can access the source: https://github.com/driftyco/ionic/blob/1.x/js/angular/service/actionSheet.js#L1

And all of the source code is here: https://github.com/driftyco/ionic/tree/1.x

**Comment by mhartington** [comment]
fixing now

**Comment by chroda** [comment]
thx guys!

**Comment by mhartington** [comment]
Fix now in master, just need to let CI take it from here and deploy. Closing for now
