### ISSUE TITLE
 ionic official forum can`t login?

### ISSUE THREAD

**Issue by 312977** [driftyco/ionic-site#707]
can you tell me why the ionic official forum can`t login?

allways show:There is a problem with your account. Please contact the site's administrator.

But there is no administrator's contact information

**Comment by mhartington** [comment]
Can you provide your user name on the forum?

**Comment by 312977** [comment]
312977493@qq.com  thank you very much

**Comment by mhartington** [comment]
There is not account associated with that email on the forum.

**Comment by 312977** [comment]
go to https://apps.ionic.io/login,
by  312977493@qq.com  can login from here: https://apps.ionic.io/login   ,when login successed,

redirecte to https://apps.ionic.io/apps,

but when goto page https://forum.ionicframework.com/,when i Click login on this page:
get an erorr,
why?,  my password is 19860922q ,can you test ?
