### ISSUE TITLE
ionic throttle and debounce missing doc

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#710]
_From @R1Daneel on July 20, 2016 7:40_

I saw that the global object `ionic` exposes two interesting methods:

- throttle

- debounce

But I did find any official doc for ionic 1.x that describes them. Is there a reason for which they are not documented?

_Copied from original issue: driftyco/ionic#7373_

**Comment by mhartington** [comment]
These are more for internal functionality and not meant to used publicly.
