### ISSUE TITLE
item-sliding fireSwipeEvent method

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#717]
_From @BugsBunnyBR on July 22, 2016 2:7_

#### Short description of the problem:

The method `fireSwipeEvent`is listed in the docs [here](http://ionicframework.com/docs/v2/api/components/item/ItemSliding/) but is marked as `private` [here](https://github.com/driftyco/ionic/blob/master/src/components/item/item-sliding.ts#L342).

It would be nice to sync the docs and source.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
Plus, I would like to have a way to slide an item to open programatically. It is not always intuitive to users the slide movement, but a button with an action that animates the slide could help to show how. To enable that, a public version of something like `fireSwipeEvent`would help.

**Which Ionic Version?** 2.x

Thanks

_Copied from original issue: driftyco/ionic#7398_

**Comment by jjmax75** [comment]
Is there any way to programmatically call the fireSwipeEvent?

item-sliding is a really cool feature, but I'm not sure the slide action is intuitive to my users

A way to call the fireSwipeEvent on (click) would be brilliant

@BugsBunnyBR did you figure this out?

**Comment by mhartington** [comment]
Fixed in master!

**Comment by BugsBunnyBR** [comment]
Hi @jjmax75 , I didn't find a proper way to do it. As this issue was moved to ionic-site I created another one just for the feature request (https://github.com/driftyco/ionic/issues/7440).

Thanks for the attention Mike! :-D

**Comment by tspriyaa** [comment]
@jgw96 I have the same issue. I would like to programmatically fire swipe event on button click (button being against each list item). Could you pls share the code to do the same, and call fireSwipeEvent. Thanks!
