### ISSUE TITLE
Ionic 2 Side menu not working correctly in some android and IOS device

### ISSUE THREAD

**Issue by Ghayyas** [driftyco/ionic-site#718]
Hi, 
 I have side menu on home page. When user click on logout sidemenu is closed and app will redirect to signin page. But the problem is Sometimes It successfully close the menu and redirect to signin Page and Sometimes menu is not closed and it stills open on signin page and on IPhone when I swipe sidemenu is open with white blank Screen and nothing is shown and im not be able to close the sidemenu.

**Comment by mhartington** [comment]
Hey there! So it looks like your issue is not related to the ionic site repo, but rather a framework question/issue. Please open an issue on the ionic repo

https://github.com/driftyco/ionic
