### ISSUE TITLE
Documentation for Header is broken

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#728]
_From @simpsondigital on July 27, 2016 17:11_

#### Currently there is nothing present.

**Steps to reproduce:**
1. Visit page above.

**Which Ionic Version?** 2.x

_Copied from original issue: driftyco/ionic#7445_

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic/commit/1c596556c5e0ce0986328c981cc2dc19149e429b
