### ISSUE TITLE
Different template names for starters

### ISSUE THREAD

**Issue by balasivagnanam** [driftyco/ionic-site#730]
Currently we are looking at different templates for creating an app.
`$ ionic start MyIonic2Project tutorial --v2`

can we include a list of all other templates that can be used to create a project?
`$ ionic start MyIonic2Project [templateName] --v2`

**Comment by mhartington** [comment]
This is there for V1 with `ionic start --list`, but not for V2 currently. You could open an issue on the CLI repo. But for now, the available templates are tabs, sidemenu, tutorial, and blank! 😁
