### ISSUE TITLE
Wrong Instructions on ./app/app.ts

### ISSUE THREAD

**Issue by hotpixelgroup** [driftyco/ionic-site#736]
[http://ionicframework.com/docs/v2/getting-started/tutorial/project-structure/](http://ionicframework.com/docs/v2/getting-started/tutorial/project-structure/)

In the **./app/app.ts** section, the docs incorrectly state we should see:

`@Component({
  templateUrl: 'build/app.html'
})`

What is actually there is:

`@Component({
  template: '<ion-nav [root]="rootPage"></ion-nav>'
})`

**Comment by hotpixelgroup** [comment]
Omitted the 'tutorial' from the 'ionic start ...' command. Gonna close and get some coffee... ;)

**Comment by brandyscarney** [comment]
I created a separate issue to update the starters so that they will have consistent project structures. :) Thanks! https://github.com/driftyco/ionic2-app-base/issues/49
