### ISSUE TITLE
Nav transition promises hard to find

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#744]
I have noticed that even though we have [this](http://ionicframework.com/docs/v2/api/components/nav/NavController/#nav-transition-promises) section of the docs we still seem to get alot of issues about users trying to do multiple transitions/navigations without using promises. I think the issue may be that you have to dig through the api docs a little to find this, although it should definitely be in the api docs and not the component docs. Therefore, one of our users had the idea of adding something about using the nav transition promises into the FAQ section of the docs.

**Comment by jgw96** [comment]
related: https://github.com/driftyco/ionic/issues/7543 , https://github.com/driftyco/ionic/issues/7554

**Comment by Kobzol** [comment]
The NavController API docs state in the section Asynchronous Nav Transitions that chaining navigation promises is a "best practice", which seems a bit misleading, because currently it is necessary to chain them or the app will break.
