### ISSUE TITLE
`improve this doc` links are not working

### ISSUE THREAD

**Issue by DomiR** [driftyco/ionic-site#749]
#### Short description of the problem:
Links for `improve this doc` are pointing into the void.

Example: 
http://ionicframework.com/docs/v2/api/components/list/List/
https://github.com/driftyco/ionic/edit/master//Users/mhartington/GitHub/ionic/src/components/list/list.ts#L6

#### What behavior are you expecting?
Should land on the right target

**Steps to reproduce:**
1. Visit http://ionicframework.com/docs/v2/api/components/list/List/
2. Click on `improve this doc`

**Which Ionic Version?** 1.x or 2.x
2

**Comment by mhartington** [comment]
Sorry about that!

_bad build process..._

Should be fixed now!

**Comment by dudeofawesome** [comment]
It looks like this is happening again.

When I click on the button on [NavController](https://ionicframework.com/docs/v2/api/navigation/NavController/), it sends me here: https://github.com/driftyco/ionic/edit/master//Users/briandennis/Ionic/ionic/src/navigation/nav-controller.ts#L4

I tested on a few other pages too, and the same thing happened.
