### ISSUE TITLE
docs: convert any optional parameters to new syntax 

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#751]
This issue has the proper syntax: https://github.com/driftyco/ionic-site/issues/558

```
@param {string} [awesomeParamName] description here.
```

Example API doc with optional: http://ionicframework.com/docs/v2/api/components/slides/Slides/#slideTo

**Comment by mhartington** [comment]
will be working on this today

**Comment by mhartington** [comment]
Looking good so far. Closing this for now as most of the public methods that need it are already taken care of.
