### ISSUE TITLE
docs: How to use Ionicons in Ionic 2 application?

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#753]
_From @rhuldip on August 10, 2016 15:5_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please provide a documentation to use Ionicons in Ionic 2 applications.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#7640_

**Comment by mhartington** [comment]
This is already covered in the component docs and the API docs

http://ionicframework.com/docs/v2/components/#icons

http://ionicframework.com/docs/v2/api/components/icon/Icon/
