### ISSUE TITLE
docs: The splash.psd does not work at its current size

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#755]
_From @flashquartermaster on August 11, 2016 14:10_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The Photoshop Splash Screen Template that is downloadable from http://ionicframework.com/docs/cli/icon-splashscreen.html does not generate anything when 'ionic resources --splash' is run until it is resized from 2732 x 2732 to 2208 x 2008. Would it be a good idea to have it at that size to begin with?</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#7666_

**Comment by mhartington** [comment]
The splashscreen needs to be that large to support the much larger ipad Pro.
Tested with the CLI 2.0 and it does upload and generates the correct splash screens.
