### ISSUE TITLE
Noto-Sans font not being loading

### ISSUE THREAD

**Issue by chrisgriffith** [driftyco/ionic-site#756]
Loading this page, as an example, http://ionicframework.com/docs/v2/api/components/infinite-scroll/InfiniteScroll/
Will report in the console log the following
Error 404 http://ionicframework.com/docs/v2/fonts/noto-sans-bold.ttf

**Comment by brandyscarney** [comment]
Are you still seeing this? I'm not able to reproduce.

**Comment by chrisgriffith** [comment]
Sorry for the late response. It seems to be resolved.
