### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#768]
_From @Devinsuit on August 24, 2016 15:34_

#### Short description of the problem:
Broken link on page http://ionicframework.com/docs/v2/api/components/nav/NavController/ 

- tab  link http://ionicframework.com/docs/v2/api/components/Tabs/Tab/ (http://ionicframework.com/docs/v2/api/components/tabs/Tab/  works)

- menu  link http://ionicframework.com/docs/v2/api/components/Menu/Menu/ (http://ionicframework.com/docs/v2/api/components/menu/Menu/  works)

**Which Ionic Version?**  2.x

_Copied from original issue: driftyco/ionic#7852_

**Comment by Devinsuit** [comment]
http://ionicframework.com/docs/v2/api/components/tabs/Tab/  

- Each ion-tab is a declarative component for a [NavController](http://ionicframework.com/docs/v2/api/components/tabs/NavController/).  (http://ionicframework.com/docs/v2/api/components/nav/NavController/ works)
