### ISSUE TITLE
docs: API v2.0.0-beta.10 redirects to the latest release

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#773]
Steps to reproduce:

1. Go to the API docs: http://ionicframework.com/docs/v2/api/
2. Click the dropdown menu and go to `2.0.0-beta.10`
3. Click on one of the options in the side menu and see it navigates to the latest release

Going directly to the URL works, for example: http://ionicframework.com/docs/v2/2.0.0-beta.10/api/components/alert/Alert/

It seems like the sidemenu links weren't generated properly for beta 10. Going down the versions I am seeing the correct links for 9 and below.

**Comment by briandennis** [comment]
Fixed with  6fbdcccaef666236fc959d2984e03df683ce2d2c.

This will need to be done manually when the version is bumped for the time being.
