### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Devinsuit** [driftyco/ionic-site#777]
http://ionicframework.com/docs/v2/components/#navigation - [those in iOS](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Navigation.html)

http://ionicframework.com/docs/v2/faq/ - [NgForm](https://angular.io/docs/js/latest/api/core/NgForm-class.html) & [NgFormModel](https://angular.io/docs/js/latest/api/core/NgFormModel-class.html) & [forwardRef](https://angular.io/docs/ts/latest/api/core/forwardRef-function.html) & [NgControlName](https://angular.io/docs/js/latest/api/core/NgControlName-class.html)

http://ionicframework.com/docs/v2/components/#navigation - [<ion-navbar>](http://ionicframework.com/docs/v2/api/components/navbar/NavBar/)

http://ionicframework.com/docs/getting-help/ - [your user environment](http://ionicframework.com/docs/cli/info)

http://ionicframework.com/docs/v2/resources/developer-tips/ - [CLI](http://ionicframework.com/docs/v2/resources/resources/what-is/#cli)

http://ionicframework.com/docs/v2/api/components/tabs/Tabs/ - [config](http://ionicframework.com/docs/v2/api/components/config/Config/)

http://ionicframework.com/docs/v2/api/components/nav/Nav/ - [Tab](http://ionicframework.com/docs/v2/api/components/Tabs/Tab/)

http://ionicframework.com/docs/v2/api/components/segment/Segment/ - [ Angular FormBuilder](https://angular.io/docs/ts/latest/api/common/FormBuilder-class.html)

http://ionicframework.com/docs/v2/api/components/tabs/Tabs/ - [NavController](http://ionicframework.com/docs/v2/api/components/tabs/NavController/)

http://ionicframework.com/docs/v2/api/components/nav/NavController/ - [Menu](http://ionicframework.com/docs/v2/api/components/Menu/Menu/) & [Tab](http://ionicframework.com/docs/v2/api/components/Tab/Tab/)

http://ionicframework.com/docs/v2/api/components/menu/Menu/ - [ NavBar](http://ionicframework.com/docs/v2/api/components/nav/NavBar)

http://ionicframework.com/docs/v2/api/components/toolbar/Toolbar/ - [ Navbar](http://ionicframework.com/docs/v2/api/components/nav/Navbar)

http://ionicframework.com/docs/v2/native/ibeacon/ - [LocationManager ](http://ionicframework.com/docs/v2/native/ibeacon/LocationManager)

http://ionicframework.com/docs/v2/native/estimotebeacons/ - [startRangingBeaconsInRegion](http://ionicframework.com/docs/v2/native/estimotebeacons/undefined)

http://ionicframework.com/docs/v2/api/components/nav/NavPush/ - [ @Page component](http://ionicframework.com/docs/v2/api/config/Page/)

**Comment by perrygovier** [comment]
Brian, can you set these up with 301 redirects?

**Comment by nolazybits** [comment]
Any info on this please?
Trying to find some info on the Page lifecycle, which seemed to be in the NavController doc :/
Thanks

**Comment by mhartington** [comment]
@nolazybits most of these links have just moved in the process of things. The search cache we have just needs to be updated.

http://ionicframework.com/docs/v2/api/

You can always manually search for these docs.
