### ISSUE TITLE
v2 native Email composer out of date

### ISSUE THREAD

**Issue by taljacobson** [driftyco/ionic-site#781]
your docs reference a out of date repo and cordova plugin version
**old**
`
$ ionic plugin add cordova-plugin-email-composer
`
`
Repo: https://github.com/katzer/cordova-plugin-email-composer.git
`
 this repo isn't being maintained 

a newer forked repo that did work, with the same ionic native import 

**new**
`
$ ionic plugin add cordova-plugin-email 
`
`
Repo: https://github.com/hypery2k/cordova-email-plugin
`

**Comment by ramonornela** [comment]
Close issue @mlynch fix in https://github.com/driftyco/ionic-native/commit/a092a31a1ed4c286d922f0c5089d1b4bab5d46a6 wait publication in site already available in [Staging](http://ionic-site-staging.herokuapp.com/docs/v2/native/email-composer/)

Thanks

**Comment by danielsogl** [comment]
@taljacobson can you close it?
