### ISSUE TITLE
docs: Page "Using Alternate Browsers" outdated

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#782]
_From @bastiss on September 21, 2016 12:12_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The content on page "Using Alternate Browsers" is outdated.

http://ionicframework.com/docs/cli/browsers.html</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#8157_

**Comment by piotrowski** [comment]
Page was removed with CLI v3, can be closed.
