### ISSUE TITLE
Ionic Native pages breaking Jekyll build

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#784]
Currently Ionic Native creates a page with the filename of a sentence and URL. This causes problems for Jekyll build. Please investigate and fix.

**Comment by briandennis** [comment]
Fixed with 11f16675bab547d2b208087491c1bb27fd6259e2

The directory with the sentence was cause by a plugin description being processed as a plugin name in one of the ionic-native source files. This was fixed with driftyco/ionic-native@c7a5f7d02378e7e3a03ae8170d5e5021327d747a
