### ISSUE TITLE
Tutorial template not working

### ISSUE THREAD

**Issue by amitmerchant1990** [driftyco/ionic-site#791]
Hi,

When firing the below command 

`ionic start MyIonic2Project tutorial --v2`

it throws below error.
![ionic-error](https://cloud.githubusercontent.com/assets/3647841/18832755/de1a51da-840a-11e6-9f45-318ee481423f.JPG)

It doesn't able to locate the repo  https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip and it certainly is not there. Kindly please look into it.

Thanks!

**Comment by mhartington** [comment]
it's possible you have an outdated CLI, as it's not honoring the `--v2` flag and is trying to pull from a V1 starter.

https://github.com/driftyco/ionic2-starter-tutorial

This is the correct repo for starter. 
CLI version : 2.1.0

![screen shot 2016-09-28 at 12 51 44 pm](https://cloud.githubusercontent.com/assets/2835826/18923515/82d02400-857a-11e6-8cd9-1374f4b4e450.png)
