### ISSUE TITLE
button docs are incorrect

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic-site#797]
As per https://github.com/driftyco/ionic/commit/938864e8d0d82a131089119b896a91006947fda6

[Button docs](http://ionicframework.com/docs/v2/components/#buttons) still suggest

``` html
<button>Button</button>
```

This should be

``` html
<button ion-button>Button</button>
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are currently in the process (literally as im typing this haha) of updating the docs site to the latest release, RC.0, which includes the correct button docs. Thanks!
