### ISSUE TITLE
tutorial docs are incorrect for latest ionic cli (v2.1.0)

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic-site#798]
Current docs [project structure](http://ionicframework.com/docs/v2/getting-started/tutorial/project-structure/) suggests that the tutorial app creates file `./app/app.ts`.

As per ionic cli 2.1.0, this instead bootstraps an ionic 2.0.0-rc.0 app, which instead uses `app.component.ts` and `app.module.ts` files.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are currently working on releasing the updated docs site (literally as i type this haha) for the RC.0 release which will fix this. Thanks!

**Comment by fiznool** [comment]
Ok, thanks. It would have been nice to have the docs ready at the same time as releasing RC.0, would have saved me some hours of frustration today. Looking forward to seeing them soon :smile:
