### ISSUE TITLE
docs: 'Demo Source' links 404

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic-site#799]
Clicking on a 'Demo Source' link in the docs results in a 404, as the URL should point to `src` folder instead of `app`.

Current link (example): https://github.com/driftyco/ionic-preview-app/tree/master/app/pages/inputs/inline

Should be: https://github.com/driftyco/ionic-preview-app/tree/master/src/pages/inputs/inline

**Comment by mhartington** [comment]
fixed.
