### ISSUE TITLE
Syntax error in code example

### ISSUE THREAD

**Issue by bdoner** [driftyco/ionic-site#825]
On [this page](http://ionicframework.com/docs/v2/resources/app-scripts/) under `Ionic Environment Variable` the code sample uses a wrong kind of quotes, does not properly escape a quote as well as not closing a string properly in a `console.log` call.

**Comment by mhartington** [comment]
Thanks! Should be fixed via

https://github.com/driftyco/ionic-site/commit/49c66673a971ce15b540e369be77c7e23c7bd34a#diff-c54b9e686d957ec5b262381bfa998169L119

The site wont update automatically but I will close this issue for now.
