### ISSUE TITLE
IonicBootstrap is not getting imported from ionic-angular

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#842]
_From @Mukul19jain on October 18, 2016 11:52_

I just started a new ionic 2 app using start command. Then I tried to import **"ionicBoostrap"** from **ionic-angular** and it gave me typescript error that "module ionic-angular has no exported member ionicBootstrap". The thing is that I need to implement ng2-translate in my project and I am following this ionic 2' documentation: 
https://ionicframework.com/docs/v2/resources/ng2-translate/

Can anyone help me out here that why I can't use ionicBootstrap the way they have used in official documentation in above link?

Thanks

_Copied from original issue: driftyco/ionic#8771_

**Comment by mhartington** [comment]
The docs needs to be updated.

**Comment by jgw96** [comment]
Yep, working on this now. Ill be submitting a pr here soon.

**Comment by jgw96** [comment]
PR for this issue https://github.com/driftyco/ionic-site/pull/843

**Comment by jgw96** [comment]
Closing as this was fixed in the above linked PR.
