### ISSUE TITLE
Ionicons page broken

### ISSUE THREAD

**Issue by karlpatrickespiritu** [driftyco/ionic-site#876]
Tried on latest version of firefox and chrome. Has JS errors.

![image](https://cloud.githubusercontent.com/assets/10472504/20374446/9bad3f3e-acb3-11e6-820b-5fcd19d28c38.png)

Would love to fix this but I'm a bit busy at work. Hopefully this will be fixed soon. Thanks!

**Comment by perrygovier** [comment]
thanks, just deployed it, and I need to bust the cache, on it now. Just a few mins.

**Comment by perrygovier** [comment]
fixed, still have some cleanup to do, but it's functional again

**Comment by karlpatrickespiritu** [comment]
thanks @perrygovier
