### ISSUE TITLE
Can't scroll LHS menu

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic-site#877]
http://ionicframework.com/docs/v2/components

The LHS menu doesn't scroll, meaning I can't reach the components at the bottom of the list.

**Comment by dylanvdmerwe** [comment]
LHS menu not scrolling on Components and API section. Tested on Safari and Chrome.

**Comment by jiricrispeyn** [comment]
#879

**Comment by jiricrispeyn** [comment]
Opened #879 to allow scrolling inside the nav

**Comment by perrygovier** [comment]
Whoop! Jekyll wasn't parsing some vars the same way on the server as it did locally. All fixed up now.

**Comment by embarq** [comment]
@perrygovier Thanks for good job!
