### ISSUE TITLE
Firefox input styling issues

### ISSUE THREAD

**Issue by jiricrispeyn** [driftyco/ionic-site#880]
Search input elements (v2 docs) on Firefox have some styling issues.
- Firefox placeholder color is incorrect (missing style?)
- Too much vertical padding causes text being cut off in Firefox

<img width="500" alt="screen shot 2016-11-17 at 13 41 34" src="https://cloud.githubusercontent.com/assets/3664238/20389770/a6b00f8e-accb-11e6-86f0-d9bba9f443bf.png">

<img width="230" alt="screen shot 2016-11-17 at 13 41 19" src="https://cloud.githubusercontent.com/assets/3664238/20389778/a8912716-accb-11e6-8b13-6dcdfc8ccba2.png">

**Comment by jiricrispeyn** [comment]
This is still an issue on the version that is currently live, yes. See issue #880 for clarification.

**Comment by perrygovier** [comment]
fixed in a6cfe3e89e309f5b230e00bb361ebfc890fc57d5
