### ISSUE TITLE
docs: incorrect syntax for buttons with only icons

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-site#884]
This is the incorrect syntax for a button with icon only: http://ionicframework.com/docs/v2/components/#toolbar-buttons

We should verify that the markup is correct elsewhere for `icon-only`, `icon-left`, and `icon-right` as well.

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic-site/commit/cb575b83b4fa1cf8b188fc26f642e55a04c01cb9
