### ISSUE TITLE
404 errors when using search bar

### ISSUE THREAD

**Issue by maxvanloosbroek** [driftyco/ionic-site#896]
Hi,

I'm new to programming and I need to look up on a lot of stuff while learning to use Ionic2.

I love the framework and how it's developing so fast, however I've run into a lot of dead ends on the documentation sites when using the search functionality. It often finds exactly what I'm looking for, only to then give a 404 error when I click the link. If I go look for the page manually it doesn't exist (anymore).

One example:
Looking for animation, the search bar immediately finds a link which doesn't work: http://ionicframework.com/docs/v2/api/animations/Animation/

This is the most recent 404, but I've encountered others, that I've forgotten.

I understand that the docs constantly change, but maybe you could look into why the search functionality still suggests these removed pages.

Max

**Comment by maxvanloosbroek** [comment]
Another one: http://ionicframework.com/docs/v2/native/Status%20Bar/

**Comment by perrygovier** [comment]
Both of these work for me. I believe you had an outdated cache
