### ISSUE TITLE
ion-input properties: whuch are possible values for 'mode' property?

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#899]
_From @chrisbenseler on November 23, 2016 11:23_

I was reading Ionic 2 docs, in the [ion-input](https://ionicframework.com/docs/v2/api/components/input/Input/) is possible to set a 'mode' property which receives a string. But which are the possible values for this?

I looked in the [input specs from HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), there's no 'mode' attribute in input element.

_Copied from original issue: driftyco/ionic#9305_

**Comment by brandyscarney** [comment]
We should modify the description for mode everywhere to include the possible values: `"md"`, `"ios"`, and `"wp"`. Maybe link to the theming docs here: http://ionicframework.com/docs/v2/theming/platform-specific-styles/.
