### ISSUE TITLE
Explaining typescript up front

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#910]
On our [tutorial page](http://ionicframework.com/docs/v2/setup/tutorial/) we very briefly mention TypeScript but with no explanation of what it actually is. We should consider adding a link to [this resource article](http://ionicframework.com/docs/v2/resources/typescript/) on that page.

**Comment by jgw96** [comment]
@mhartington id love your feedback on this idea when you get time!

**Comment by mhartington** [comment]
No need for a new resource page, we could just link to here 

http://ionicframework.com/docs/v2/resources/what-is/#typescript
