### ISSUE TITLE
404 error when navigating to "Navigating to Pages" from the Getting Started tutorial 

### ISSUE THREAD

**Issue by albertorcf** [driftyco/ionic-site#912]
Link: http://ionicframework.com/docs/v2/getting-started/tutorial/navigation
Label: Navigating to Pages
Result: 404 error page

**Comment by mhartington** [comment]
The page has been moved.
http://ionicframework.com/docs/v2/setup/tutorial/

**Comment by brandyscarney** [comment]
The site is most likely cached. Try doing a hard reload of the site and you should see the sidemenu change to have a link for "setup". :smile:
