### ISSUE TITLE
"Components" & "Theming" Cards without links to documentation

### ISSUE THREAD

**Issue by jorge-sanz** [driftyco/ionic-site#913]
<img width="1280" alt="screen shot 2016-11-30 at 7 57 38 pm" src="https://cloud.githubusercontent.com/assets/5048292/20766616/65920248-b737-11e6-8e61-ecca444882c2.png">

Links to components and theming documentation part are missed here at the end of the [Getting Started page](http://ionicframework.com/getting-started/). Like "Ionic Native" card has.

**Comment by mhartington** [comment]
Hmm, they're all links for me. And they're links in the source as well
https://github.com/driftyco/ionic-site/blob/master/getting-started/index.html#L123-L144

Can you clear your browser cache?

**Comment by jorge-sanz** [comment]
True!
