### ISSUE TITLE
ionic ion-navbar color attribute enhancement 

### ISSUE THREAD

**Issue by Jonatthu** [driftyco/ionic-site#917]
I would like to have the option on the same color attr oh this component to put an hex color as string and detects that is not a sass variable.

  <ion-navbar color="#333333">
    <ion-title>Home</ion-title>
  </ion-navbar>

  <ion-navbar color="primary">
    <ion-title>Home</ion-title>
  </ion-navbar>

I need to be able to change the color through a service and then the component make the change, but because the color never will be the same or a known color I can't not use sass variables.

Is there a way now to do it?
Or I need to inherit the directive color and modify it?
What is the best approach ?

Thanks!

**Comment by mhartington** [comment]
First off, this is not the appropriate place for this issue. 

Secondly, this is not possible, since the color is property sets a predefined class, not an arbitrary color. 
So this would not be possible.

**Comment by Jonatthu** [comment]
Yes I just notice I came to here fro ionic documentation with the wrong link.
