### ISSUE TITLE
docs: V1 Javascript/API documentation links broken

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#922]
_From @gumbootphil on December 6, 2016 0:57_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In case you don't already know the V1 documentation for the Javascript section are al returning 404 errors eg:

https://ionicframework.com/docs/v1/api/directive/ionSlides/

Keep up the great work!</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#9506_

**Comment by jgw96** [comment]
Hmm looks like you may have an old link. [This](https://ionicframework.com/docs/api/directive/ionSlides/) is the correct link to that v1 component. Where did you get that link from?

**Comment by perrygovier** [comment]
I can't find refference to this link. Closing until @gumbootphil can reply
