### ISSUE TITLE
docs: Quick update to your install instruction: sudo

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#936]
_From @jakedemian on December 20, 2016 2:48_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>For the install instructions, running the exact command from your guide "npm install -g cordova ionic" gave me errors, I needed to add sudo to the front so that I had access permissions to touch the necessary files.  I just think that it would probably be beneficial to mention this for the mac/linux users out there that might run into that issue and not know the solution.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#9717_

**Comment by mhartington** [comment]
http://ionicframework.com/docs/v2/setup/installation/

Already there.
