### ISSUE TITLE
(docs): preview of mobile view is not showing fully

### ISSUE THREAD

**Issue by tjnapster555** [driftyco/ionic-site#941]
In the docs the mobile preview of the code is not showing correctly , need to lower the size of mobile preview so we can see it correctly.
check this ![Tab not showing correctly](http://i.imgur.com/Af6Q0nv.png)

**Comment by perrygovier** [comment]
fixed in https://github.com/driftyco/ionic-site/commit/dec87073a903292f09a938c113a9998dc4017689

This should be live in a day or two. Thanks!
