### ISSUE TITLE
Fix the FAB demo

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#947]
http://ionic-site-staging.herokuapp.com/docs/v2/api/components/fab/FabList/

This started breaking a week or two ago. It's not in production, but it's holding up staging from getting promoted.

**Comment by brandyscarney** [comment]
I'm 99% sure it's because of this index file: https://github.com/driftyco/ionic/blob/master/demos/src/fab/index.html

Just need to test it on master.
