### ISSUE TITLE
[docs] - Slides pager property is wrongly documented.

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic-site#959]
The pager property of Slides component is wrongly documented. Currently the doc indicates this: 

attr: pager
type: boolean	
details: String with type of pagination. Can be bullets, fraction, progress. Default does not have pagination set.

http://ionicframework.com/docs/v2/api/components/slides/Slides/

**Comment by brandyscarney** [comment]
Fixed by https://github.com/driftyco/ionic/pull/9968, just needs to be deployed. :)

**Comment by brandyscarney** [comment]
This is fixed in the nightly: http://ionicframework.com/docs/v2/nightly/api/components/slides/Slides/
