### ISSUE TITLE
[docs]: split each component into it's own page, similar to api docs.

### ISSUE THREAD

**Issue by AlQuraian** [driftyco/ionic-site#962]
Thank you for all the people who worked on the documentation website for Ionic, it's probably one of the best and easiest docs I've seen.

The request is to make each component documentation into a separate page, in similar fashion to the api docs.

The reasons for this are:
- It's less confusing as sometimes when you are scrolling you move into the next component which may cause some confusion, also sometimes the demo shows the screen for the above component.
- When searching for something within a given component the results set will show results for the current component's page only, not for all components (easier to find things).
- Less load on server and client.

**Comment by perrygovier** [comment]
Thanks, we believe it's more important to let users unfamiliar scroll through and "window shop" ionic components when they're first learning what the framework can do. 

I think by making the header bar fixed and update as you scroll, it should help with some of the confusion, though. That's in issue #949. 

I get the concern, but for this section, the initial impression to new users is more important.
