### ISSUE TITLE
Moving between Menu and Modal doesn't work for the modals example in v2 Docs

### ISSUE THREAD

**Issue by nitinthewiz** [driftyco/ionic-site#975]
Steps to repro - 
1. Be on latest Chrome on Win 10 looking at iOS examples of v2
2. Be here - http://ionicframework.com/docs/v2/components/#menus
3. Open sample menu by clicking the burger or the "toggle menu" button. Sample screen shifts right to show side menu
4. Keep scrolling to get to modals sample
5. Sample screen loads modals on main screen, but burger disappears and side menu remains. 
6. If you click on one of the modal buttons, modal probably loads, leaving no way to close side menu other than to reload page. Scrolling back to Menu docs doesn't show burger menu again.
7. If you don't click on the modals, scrolling back to the Menu docs *does* show the burger button, which can then be used to close menu.

Solution - detect if menu is open. If menu is open, burger button should always be shown. Also, if menu is open, main screen buttons should not be clickable.

I clicked Improve this Doc, but I get a 404. You're probably moving things around for v2 launch.

**Comment by perrygovier** [comment]
Thanks!
