### ISSUE TITLE
Ionic view source throws 404 

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#985]
_From @aravindfz on February 3, 2017 4:25_

**Ionic version:** 
[x] **1.x**

In the [Ionic Collection](http://ionicframework.com/docs/api/directive/collectionRepeat/) documentation 
Clicking on the View Source navigates me to a github page [here](https://github.com/driftyco/ionic/tree/1.x/js/angular/directive/collectionRepeat.js#L2)
**I'm submitting a documentation error** 
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
404 Not Found 

**Expected behavior:**
Source Documentation 

_Copied from original issue: driftyco/ionic#10294_

**Comment by perrygovier** [comment]
fixed in b4e1b57ee43f2a3ef8d008db9d84b7140f24d568
