### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#988]
_From @Fakkio on February 5, 2017 22:57_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a documentation error

in https://ionicframework.com/docs/v2/api/navigation/NavController/ is written that the first argument of remove() method is optional, but it is required instead.

_Copied from original issue: driftyco/ionic#10321_

**Comment by mhartington** [comment]
closed via https://github.com/driftyco/ionic/commit/fae38f910c2a44a57d7769ad09e9235f38f0a2d6
